import dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });
import axios from 'axios'
import { embed } from './ollama.js';

const ingredients = [
  {
    name: 'Vitamin C',
    description: 'Also known as L-Ascorbic Acid. Water-soluble vitamin and potent antioxidant essential for collagen synthesis, immune function, and wound healing. Humans cannot synthesise Vitamin C and must obtain it from diet. Enhances non-haem iron absorption from plant foods. Found abundantly in citrus fruits, bell peppers, kiwi, broccoli, and strawberries.',
    purpose: 'Antioxidant, immune support, collagen synthesis, and enhances iron absorption',
    safety_notes: 'Safe at recommended doses. Very high doses (above 2g/day) may cause GI upset, diarrhoea, and kidney stone formation in susceptible individuals. Absorption efficiency drops significantly above 1g/day. People with haemochromatosis (iron overload) should be cautious — Vitamin C enhances iron absorption.',
    is_common_allergen: false,
    category: 'vitamin',
    severity: 'safe',
    bioavailability: 'high',
    bioavailability_notes: 'Well absorbed at doses below 200mg; absorption efficiency decreases at higher doses. Take with food to reduce GI upset.',
  },
  {
    name: 'Liposomal Vitamin C',
    description: 'Vitamin C encapsulated within phospholipid liposomes — tiny fat-soluble vesicles that protect Vitamin C from digestive breakdown and allow it to be absorbed directly into cells. The Vitamin C itself is industrially produced Ascorbic Acid (same as standard Vitamin C supplements); the liposomal encapsulation is the delivery system, not the source. Achieves higher plasma levels than standard oral Vitamin C at equivalent doses.',
    purpose: 'Enhanced-absorption Vitamin C for immune support, antioxidant protection, and collagen synthesis',
    safety_notes: 'Safe — same overall safety profile as Vitamin C. Phospholipid shell is typically from sunflower or soy lecithin — check label if you have a soy allergy. May cause fewer GI side effects than standard Vitamin C at equivalent doses.',
    is_common_allergen: false,
    category: 'vitamin',
    severity: 'safe',
    bioavailability: 'high',
    bioavailability_notes: 'Liposomal encapsulation bypasses GI absorption limits, achieving higher plasma levels than standard Vitamin C at equivalent doses.',
  },
  {
    name: 'Ascorbic Acid',
    description: 'The pure chemical form of Vitamin C (L-Ascorbic Acid). Commercially produced via bacterial/fungal fermentation of glucose — not extracted from fruit despite Vitamin C occurring naturally in citrus. The most economical and widely available supplement form, identical in biological activity to food-sourced Vitamin C. Slightly acidic — can irritate the GI tract at high doses in sensitive individuals.',
    purpose: 'Antioxidant, immune support, collagen synthesis, and iron absorption enhancement',
    safety_notes: 'Safe at recommended doses. At high doses (above 2g/day) may cause GI distress and loose stools. Acidic pH may irritate the stomach in sensitive individuals — buffered forms (Calcium Ascorbate, Sodium Ascorbate) are gentler alternatives. Same kidney stone caution as Vitamin C applies in susceptible individuals.',
    is_common_allergen: false,
    category: 'vitamin',
    severity: 'safe',
    bioavailability: 'high',
    bioavailability_notes: 'Identical bioavailability to food-sourced Vitamin C at doses below 200mg. Buffered forms (e.g. calcium ascorbate) may be gentler on the stomach.',
  },
  {
    name: 'Natural Acerola Cherry Concentrate',
    description: 'Derived from the Acerola cherry (Malpighia emarginata) — one of the richest natural sources of Vitamin C, containing up to 65× more Vitamin C per gram than oranges. Unlike synthetic Ascorbic Acid, Acerola Vitamin C comes packaged with naturally occurring bioflavonoids and other phytonutrients. Used in supplements as a natural-source Vitamin C alternative.',
    purpose: 'Whole-food source of Vitamin C with synergistic bioflavonoids for antioxidant and immune support',
    safety_notes: 'Safe. Same general safety profile as Vitamin C. Very rare cherry-related allergies reported — avoid if known stone fruit allergy. Vitamin C content can vary significantly between batches — check standardised Vitamin C content on product label.',
    is_common_allergen: false,
    category: 'extract',
    severity: 'safe',
    bioavailability: 'high',
    bioavailability_notes: 'Naturally occurring Vitamin C with co-factor bioflavonoids may improve tissue retention compared to isolated ascorbic acid.',
  },
  {
    name: 'Citrus Bioflavonoids',
    description: 'A group of polyphenolic plant compounds found in citrus fruits, including hesperidin, rutin, quercetin, naringenin, and diosmin. Historically paired with Vitamin C as they appear to enhance its activity and improve capillary strength. Used for venous insufficiency, haemorrhoids, and general antioxidant support.',
    purpose: 'Antioxidant plant compounds that support capillary integrity, reduce inflammation, and enhance Vitamin C absorption',
    safety_notes: 'Generally safe at supplement doses. May interact with certain medications metabolised by the CYP3A4 enzyme (statins, calcium channel blockers) — similar to but less potent than grapefruit interaction. Rare allergic reactions in citrus-sensitive individuals.',
    is_common_allergen: false,
    category: 'extract',
    severity: 'safe',
    bioavailability: 'medium',
    bioavailability_notes: 'Absorption varies by specific bioflavonoid compound. Takes several hours to reach peak blood levels.',
  },
  {
    name: 'Magnesium Stearate',
    description: 'A magnesium salt of stearic acid used as a manufacturing lubricant in tablets and capsules. Found in the vast majority of commercial supplements — it prevents ingredients from sticking to tablet press machinery during production. Not a nutrient; it is an inactive ingredient (excipient). Claims that it impairs supplement absorption are not supported by clinical evidence at concentrations used.',
    purpose: 'Manufacturing lubricant that prevents ingredients from sticking to tablet press machinery',
    safety_notes: 'Safe at amounts used in supplements (typically less than 2% of tablet weight). Not a meaningful source of magnesium. May be derived from animal or vegetable stearic acid — vegetarians and vegans should check the source on the label.',
    is_common_allergen: false,
    category: 'lubricant',
    severity: 'safe',
    bioavailability: 'na',
    bioavailability_notes: 'Inert excipient; not a nutrient source. Used in small amounts that are safe and not nutritionally meaningful.',
  },
  {
    name: 'Microcrystalline Cellulose',
    description: 'A refined plant-derived cellulose used as a binder and filler in supplement tablets. Gives tablets their structural integrity and helps them break apart in the digestive tract so active ingredients can be absorbed. Composed of indigestible fibre — it passes straight through without being absorbed.',
    purpose: 'Tablet binder and filler providing structural integrity to tablets',
    safety_notes: 'Safe — well established as inert. Recognised as GRAS by FDA. Not absorbed; passes through GI tract as insoluble fibre. No known allergenicity. Suitable for vegetarians and vegans.',
    is_common_allergen: false,
    category: 'filler',
    severity: 'safe',
    bioavailability: 'na',
    bioavailability_notes: 'Not absorbed; passes through GI tract as insoluble fibre. Inert and safe.',
  },
  {
    name: 'Maltodextrin',
    description: 'A starch-derived carbohydrate (typically from corn, wheat, or rice) used as a carrier and bulking agent in powdered supplements. Helps spray-dried extracts flow properly and improves texture. Also used in sports nutrition as a fast-digesting carbohydrate energy source. Has a high glycaemic index despite not tasting sweet.',
    purpose: 'Carrier and bulking agent for powdered supplements; improves texture, flowability, and mixability',
    safety_notes: 'Safe at supplement levels. People with diabetes or insulin resistance should be aware that Maltodextrin has a very high glycaemic index (85–105) and can spike blood sugar — relevant mainly in large amounts such as sports nutrition powders, not trace excipient amounts in capsules or tablets. People with coeliac disease should prefer corn-derived Maltodextrin over wheat-derived.',
    is_common_allergen: false,
    category: 'filler',
    severity: 'safe',
    bioavailability: 'na',
    bioavailability_notes: 'Rapidly absorbed carbohydrate with high glycaemic index. Amounts used as excipient in capsules/tablets are nutritionally negligible.',
  },
  {
    name: 'Silicon Dioxide',
    description: 'Also known as Silica. A naturally occurring mineral used as an anti-caking agent in powdered supplements to prevent clumping and improve flow during manufacturing. The form used in food and supplements is amorphous (non-crystalline) silicon dioxide — chemically inert and not absorbed by the body. Listed as E551 in food additives.',
    purpose: 'Anti-caking agent that prevents powdered ingredients from clumping in capsules and tablets',
    safety_notes: 'Safe — the amorphous form used in supplements is not associated with lung disease (only crystalline silica inhaled occupationally poses that risk — not relevant to oral consumption). Recognised as GRAS by FDA. No known allergenicity.',
    is_common_allergen: false,
    category: 'anticaking_agent',
    severity: 'safe',
    bioavailability: 'na',
    bioavailability_notes: 'Not absorbed; inert excipient. Safe at amounts used in supplement manufacturing.',
  },
  {
    name: 'Hydroxypropyl Methylcellulose',
    description: 'Also known as HPMC or Hypromellose. A plant-derived cellulose used as the shell material for vegetarian and vegan capsules — the most widely used gelatin alternative in the supplement industry. Also used as a film coating on tablets. Passes through the digestive tract without being absorbed.',
    purpose: 'Vegetarian capsule shell material; also used as a film coating agent for tablets',
    safety_notes: 'Safe — well established as inert. Not absorbed. No known allergenicity. Suitable for vegetarians, vegans, kosher, and halal diets. Does not affect absorption of active ingredients.',
    is_common_allergen: false,
    category: 'coating',
    severity: 'safe',
    bioavailability: 'na',
    bioavailability_notes: 'Not absorbed; plant-derived cellulose derivative. Suitable for vegetarians and vegans as a gelatin alternative.',
  },
  {
    name: 'Glycerin',
    description: 'Also known as Glycerol. A clear, sweet-tasting liquid used in supplements as a humectant (retains moisture), solvent, and softening agent. Keeps softgel capsules flexible, acts as a solvent in liquid supplements, and is used as a food additive (E422). Can be derived from plant oils (vegetable glycerin) or animal fats — vegetable glycerin is most common in supplements.',
    purpose: 'Humectant and solvent in liquid supplements; softening agent in softgel capsules',
    safety_notes: 'Safe — well tolerated. Absorbed and metabolised as a carbohydrate. Vegetarians and vegans should confirm vegetable source on the label. Not associated with allergenicity or drug interactions at supplement use levels.',
    is_common_allergen: false,
    category: 'humectant',
    severity: 'safe',
    bioavailability: 'high',
    bioavailability_notes: 'Absorbed and metabolised as a carbohydrate. Amounts used as excipient in supplements are nutritionally negligible.',
  },
  {
    name: 'Carnauba Wax',
    description: 'A natural wax derived from the leaves of the Carnauba palm tree (Copernicia prunifera) native to Brazil. Used as a tablet coating and polish to protect tablets from moisture and make them easier to swallow. Also used in food (E903) as a glazing agent for confectionery and chewing gum. One of the hardest natural waxes — entirely plant-derived.',
    purpose: 'Tablet coating and polish that protects tablets from moisture and gives a smooth, glossy finish',
    safety_notes: 'Safe — inert and not absorbed. Recognised as GRAS by FDA. Listed as E903 in food additives. No known allergenicity. Suitable for vegetarians and vegans. Used in very small quantities as a coating material.',
    is_common_allergen: false,
    category: 'coating',
    severity: 'safe',
    bioavailability: 'na',
    bioavailability_notes: 'Not absorbed; inert plant-derived wax from palm leaves. Safe at supplement use levels.',
  },
  {
    name: 'Methyl Cellulose',
    description: 'A plant-derived cellulose used as a vegetarian capsule shell material and tablet binder — one of the original gelatin alternatives in supplement manufacturing. Also used in food as a thickener (E461). Passes through the digestive tract without being absorbed. In larger doses, used as a bulk-forming laxative (sold as Citrucel).',
    purpose: 'Vegetarian capsule shell material and tablet binder; plant-derived gelatin alternative',
    safety_notes: 'Safe — inert and non-absorbed. Recognised as GRAS. No known allergenicity. Suitable for vegetarians and vegans. No drug interactions at supplement excipient amounts.',
    is_common_allergen: false,
    category: 'binder',
    severity: 'safe',
    bioavailability: 'na',
    bioavailability_notes: 'Not absorbed; passes through GI tract. Suitable for vegetarians and vegans.',
  },
  {
    name: 'Folic Acid',
    description: 'The synthetic form of Vitamin B9 (Folate), used in food fortification and most standard supplements. Must be converted by the body into the active form before it can be used. Government-mandated in flour and cereals in many countries to prevent neural tube defects during pregnancy. Essential for DNA synthesis and cell division.',
    purpose: 'DNA synthesis, cell division support, and prevention of neural tube defects during pregnancy',
    safety_notes: 'Safe at recommended doses. High intake (above 1mg/day) can mask Vitamin B12 deficiency — corrects anaemia but allows nerve damage to progress undetected. People with MTHFR gene variants cannot convert Folic Acid efficiently — unmetabolised folic acid may accumulate. These individuals should prefer Methylfolate. 400–800mcg/day recommended for women planning pregnancy.',
    is_common_allergen: false,
    category: 'vitamin',
    severity: 'safe',
    bioavailability: 'medium',
    bioavailability_notes: 'Well absorbed in the gut but requires multiple conversion steps to become active. Approximately 40% of people with MTHFR gene variants convert it poorly — prefer Methylfolate.',
  },
  {
    name: 'Niacin',
    description: 'Also known as Nicotinic Acid — the acid form of Vitamin B3. Causes "niacin flush" (skin redness, warmth, tingling) at doses above 50mg due to its vasodilating effect. At high prescription doses (1–2g/day), one of the most effective treatments for raising HDL cholesterol and lowering triglycerides. Also a precursor to NAD+ for cellular energy production.',
    purpose: 'Cholesterol management; raises HDL and lowers triglycerides at high doses; energy metabolism support',
    safety_notes: 'Caution at high doses. Skin flushing is harmless but uncomfortable — taking aspirin 30 minutes before can reduce it. High-dose Niacin (1–2g/day) should only be used under medical supervision — risk of liver toxicity, raised blood sugar, and gout flares. Extended-release Niacin carries higher liver toxicity risk than immediate-release. May interact with statins.',
    is_common_allergen: false,
    category: 'vitamin',
    severity: 'caution',
    bioavailability: 'high',
    bioavailability_notes: 'Well absorbed orally. Water-soluble; excess excreted in urine.',
  },
  {
    name: 'Thiamine',
    description: 'Also known as Vitamin B1. Essential for converting carbohydrates into energy and for healthy nerve and heart function. When a label says "Thiamine" without specifying the form, it is the basic water-soluble form with limited absorption at higher doses. Better-absorbed forms exist — Thiamine HCl (most common in supplements) and Benfotiamine (fat-soluble, reaches nerve tissue more effectively).',
    purpose: 'Energy metabolism support; essential for converting carbohydrates to energy and maintaining nerve function',
    safety_notes: 'Safe — no known toxicity at supplement doses. Water-soluble; excess excreted in urine. People at higher risk of deficiency: chronic alcohol users, those on long-term diuretics, and people with malabsorption conditions.',
    is_common_allergen: false,
    category: 'vitamin',
    severity: 'safe',
    bioavailability: 'medium',
    bioavailability_notes: 'Water-soluble; absorption becomes saturated at higher oral doses (above 5mg per dose). Active transport operates at low doses.',
  },
  {
    name: 'Riboflavin',
    description: 'Also known as Vitamin B2. Essential for cellular energy production and for activating other B vitamins (B6, folate, niacin). Gives supplements their yellow-orange colour and turns urine bright yellow at higher doses — harmless. When a label says "Riboflavin" without specifying the form, it is the basic form that requires conversion. A more bioavailable active form exists: Riboflavin-5-Phosphate (FMN).',
    purpose: 'Cellular energy production; essential for metabolism of other B vitamins and fatty acid oxidation',
    safety_notes: 'Safe — no known toxicity. Water-soluble; excess excreted in urine causing bright yellow urine — harmless and expected. Well tolerated at all supplement doses. High-dose Riboflavin (400mg/day) is used for migraine prevention.',
    is_common_allergen: false,
    category: 'vitamin',
    severity: 'safe',
    bioavailability: 'medium',
    bioavailability_notes: 'Absorption limited per dose (maximum ~27mg absorbed at once). Water-soluble. Take with food for best absorption.',
  },
  {
    name: 'Pantothenic Acid',
    description: 'Also known as Vitamin B5. Essential for energy metabolism and the production of steroid hormones, neurotransmitters, and red blood cells via Coenzyme A (CoA) synthesis. Found in virtually all foods — dietary deficiency is extremely rare. Commonly used in supplements for energy, adrenal support, and acne. Most common supplement form is Calcium Pantothenate.',
    purpose: 'Energy metabolism and stress response support; essential for CoA synthesis and adrenal hormone production',
    safety_notes: 'Safe — one of the safest vitamins. No known toxicity even at very high doses. At extremely high doses (above 10g/day) may cause diarrhoea. Water-soluble; excess excreted in urine.',
    is_common_allergen: false,
    category: 'vitamin',
    severity: 'safe',
    bioavailability: 'high',
    bioavailability_notes: 'Well absorbed at typical supplement doses. Water-soluble; excess excreted in urine.',
  },
  {
    name: 'Pyridoxine HCl',
    description: 'The most common supplemental form of Vitamin B6 — the hydrochloride salt of Pyridoxine, used in virtually all B-complex supplements due to its stability. Plain "Pyridoxine" on a label is the same compound. Must be converted by the liver to Pyridoxal-5-Phosphate (P5P) — the active form the body actually uses. People with liver conditions may not convert it efficiently — P5P is the preferred form for them.',
    purpose: 'Amino acid metabolism, neurotransmitter synthesis (serotonin, dopamine, GABA), and haemoglobin production',
    safety_notes: 'Safe at typical supplement doses (1–25mg). High doses above 200mg/day have caused peripheral neuropathy (numbness and tingling in hands and feet) — only relevant for high-dose standalone B6 supplements, not standard B-complex products. Symptoms are generally reversible on stopping.',
    is_common_allergen: false,
    category: 'vitamin',
    severity: 'safe',
    bioavailability: 'high',
    bioavailability_notes: 'Well absorbed orally. Requires liver conversion to active P5P form — conversion is efficient in healthy individuals.',
  },
  {
    name: 'Cyanocobalamin',
    description: 'The synthetic form of Vitamin B12, most commonly used in supplements and food fortification due to its stability and low cost. Must be converted in the body to the active forms (Methylcobalamin and Adenosylcobalamin) before use. Contains a small cyanide molecule that is released during conversion — the amount is negligible and harmless for most people. Better-absorbed active forms exist: Methylcobalamin and Adenosylcobalamin.',
    purpose: 'Nerve function maintenance, red blood cell production, and DNA synthesis',
    safety_notes: 'Safe — cyanide released during conversion is far below toxic levels. People with Leber hereditary optic neuropathy should use Methylcobalamin instead. Heavy smokers may have reduced ability to metabolise the cyanide component. Vegans and vegetarians, older adults, and people on long-term Metformin or proton pump inhibitors are at higher risk of B12 deficiency.',
    is_common_allergen: false,
    category: 'vitamin',
    severity: 'safe',
    bioavailability: 'medium',
    bioavailability_notes: 'Requires intrinsic factor for normal absorption. Sublingual or high-dose oral (above 1000mcg) bypasses this requirement. Must be converted to active forms in the body.',
  },
  {
    name: 'Inositol',
    description: 'A naturally occurring carbohydrate that acts as a cellular signalling molecule. While historically grouped with B vitamins, it is not a true vitamin as the body can produce it from glucose. The most common forms in supplements are Myo-inositol and D-chiro-inositol. Strong clinical evidence for PCOS management at high doses (12–18g/day of Myo-inositol). Also used for anxiety, OCD, and insulin resistance.',
    purpose: 'Supports cellular signalling, mood balance, insulin sensitivity, and PCOS management',
    safety_notes: 'Safe — one of the safest supplements available. At high doses (above 12g/day) may cause mild nausea or diarrhoea. Can lower blood sugar — people on diabetes medications should monitor glucose levels. High-dose use during pregnancy for PCOS should be discussed with a doctor.',
    is_common_allergen: false,
    category: 'other',
    severity: 'safe',
    bioavailability: 'high',
    bioavailability_notes: 'Well absorbed orally. Myo-inositol and D-chiro-inositol are the most studied and bioavailable forms.',
  },
  {
    name: 'Para-Aminobenzoic Acid',
    description: 'Also known as PABA. Once informally called "Vitamin Bx" in early nutrition research but is not a vitamin — not essential in diet and has no official B vitamin classification. Still commonly found in B-complex supplements by tradition. A structural component of folate. Also used in sunscreens (blocks UVB rays) and in a pharmaceutical form (Potaba) for certain fibrotic conditions.',
    purpose: 'Historically included in B-complex formulas; supports folic acid metabolism and is used for skin conditions',
    safety_notes: 'Generally safe at typical B-complex doses. At high pharmaceutical doses (above 8g/day as Potaba) may cause nausea, rash, and fever. Interferes with sulfonamide antibiotics — avoid concurrent use. Not recommended at high doses during pregnancy.',
    is_common_allergen: false,
    category: 'other',
    severity: 'safe',
    bioavailability: 'high',
    bioavailability_notes: 'Well absorbed orally. Not a recognised essential vitamin; considered a non-essential nutrient.',
  },
  {
    name: 'Dicalcium Phosphate',
    description: 'A calcium and phosphorus compound used in two roles: as a dietary supplement for bone health, and as a tablet filler and binder in manufacturing due to its excellent compressibility. One of the most widely used calcium sources in supplement tablets. Also listed as E341 in food additives.',
    purpose: 'Calcium and phosphorus supplement; also widely used as a tablet filler and binder in manufacturing',
    safety_notes: 'Safe at supplement doses. People with kidney disease should consult a doctor before taking high-dose calcium or phosphate supplements. May reduce absorption of iron, zinc, and magnesium if taken at the same time — space mineral supplements 2 hours apart.',
    is_common_allergen: false,
    category: 'mineral',
    severity: 'safe',
    bioavailability: 'medium',
    bioavailability_notes: 'Moderate calcium bioavailability; less bioavailable than calcium citrate. Absorption requires adequate stomach acid.',
  },
  {
    name: 'Lactose',
    description: 'A sugar naturally found in dairy milk, used in supplement manufacturing as a tablet filler and carrier. Not added as a nutrient — purely an inactive ingredient (excipient). The amount in a supplement tablet is typically very small (under 100mg) — far below the ~12g threshold that causes symptoms in most lactose-intolerant individuals.',
    purpose: 'Tablet diluent and filler in supplement manufacturing; carrier for fine active ingredients',
    safety_notes: 'Contains dairy — not suitable for people with milk allergy (IgE-mediated). Most lactose-intolerant individuals tolerate the small amounts used in tablets without symptoms, but highly sensitive individuals should avoid. Check label if dairy-free is required.',
    is_common_allergen: true,
    category: 'filler',
    severity: 'safe',
    bioavailability: 'na',
    bioavailability_notes: 'Well absorbed in most people. Not absorbed in lactose-intolerant individuals — broken down by gut bacteria instead, causing bloating and GI distress.',
  },
  {
    name: 'Calcium Stearate',
    description: 'A calcium salt of stearic acid used as a flow agent and lubricant in tablet manufacturing — similar function to Magnesium Stearate. Prevents powdered ingredients from sticking to processing equipment. The calcium content is not nutritionally significant at amounts used in supplements.',
    purpose: 'Flow agent and lubricant in tablet manufacturing; prevents powder from sticking to machinery',
    safety_notes: 'Safe at amounts used in supplements. Recognised as GRAS. Not a meaningful calcium source. May be derived from animal or vegetable stearic acid — vegetarians and vegans should check the source on the label.',
    is_common_allergen: false,
    category: 'lubricant',
    severity: 'safe',
    bioavailability: 'na',
    bioavailability_notes: 'Not a meaningful calcium source at supplement use levels. Inert excipient.',
  },
  {
    name: 'Methylcobalamin',
    description: 'The active form of Vitamin B12 found in human blood and tissues. Unlike Cyanocobalamin, it does not need to be converted — it is used directly by the body for nerve protection, methylation, and DNA synthesis. The preferred B12 form for neurological support and for people with conditions that impair B12 conversion.',
    purpose: 'Active Vitamin B12 for nerve protection, methylation support, DNA synthesis, and energy',
    safety_notes: 'Safe — no established upper tolerable intake level. Well tolerated at all standard supplement doses. Preferred over Cyanocobalamin for people with Leber optic neuropathy and heavy smokers. Vegans and vegetarians should supplement B12 regularly as it is only found in animal products.',
    is_common_allergen: false,
    category: 'vitamin',
    severity: 'safe',
    bioavailability: 'high',
    bioavailability_notes: 'Active form requiring no liver conversion. Better tissue retention than cyanocobalamin. Preferred for neurological support.',
  },
  {
    name: 'Adenosylcobalamin',
    description: 'One of the two active forms of Vitamin B12 (alongside Methylcobalamin). Works primarily in the mitochondria — essential for energy production and fatty acid metabolism. Less common in supplements than Methylcobalamin but increasingly available in active B12 products. Light-sensitive and less shelf-stable than Cyanocobalamin. Often combined with Methylcobalamin for complete B12 coverage.',
    purpose: 'Active mitochondrial Vitamin B12 for energy production and fatty acid and amino acid metabolism',
    safety_notes: 'Safe — same excellent safety profile as other B12 forms. No established upper tolerable intake level. Well tolerated at standard supplement doses. Store away from light to preserve potency.',
    is_common_allergen: false,
    category: 'vitamin',
    severity: 'safe',
    bioavailability: 'high',
    bioavailability_notes: 'Active form requiring no conversion. Light-sensitive and less shelf-stable. Often combined with Methylcobalamin for complete B12 support.',
  },
  {
    name: 'Methylfolate',
    description: 'Also known as 5-MTHF or L-Methylfolate. The active form of Vitamin B9 (Folate) — used directly by the body without conversion. The superior alternative to Folic Acid, especially for the ~40% of people with MTHFR gene variants who cannot efficiently convert Folic Acid. Crosses the blood-brain barrier to support neurotransmitter production. Patented forms include Quatrefolic and Metafolin.',
    purpose: 'Active Vitamin B9 for DNA synthesis, methylation, and mood support; preferred for MTHFR gene variants',
    safety_notes: 'Safe. A small subset of people — particularly those with certain psychiatric conditions — may experience anxiety, irritability, or insomnia when starting Methylfolate. Start with a low dose and increase gradually. Does not cause unmetabolised folate accumulation unlike Folic Acid. Safe in pregnancy.',
    is_common_allergen: false,
    category: 'vitamin',
    severity: 'safe',
    bioavailability: 'high',
    bioavailability_notes: 'Directly usable without liver conversion. Crosses blood-brain barrier. Preferred over Folic Acid for carriers of MTHFR gene mutations.',
  },
  {
    name: 'Biotin',
    description: 'Also known as Vitamin B7 or Vitamin H. Essential for fatty acid synthesis, energy metabolism, and amino acid processing. Widely marketed for hair, skin, and nail health — evidence for this benefit is limited in people without deficiency. Found naturally in egg yolk, nuts, seeds, and organ meats. Raw egg whites block Biotin absorption by binding to it in the gut.',
    purpose: 'Supports hair, skin, and nail health; essential for fatty acid synthesis and energy metabolism',
    safety_notes: 'Safe — no known toxicity. CRITICAL: High-dose Biotin (above 5mg/day, common in hair and nail supplements) causes false results in many blood tests including thyroid (TSH, T3, T4), cardiac troponin, and hormone panels. Always inform your doctor and stop Biotin at least 3–7 days before any blood test. The FDA has issued safety warnings about this.',
    is_common_allergen: false,
    category: 'vitamin',
    severity: 'safe',
    bioavailability: 'high',
    bioavailability_notes: 'Well absorbed at supplement doses. Raw egg white consumption blocks absorption — avidin protein in egg white binds Biotin in the gut.',
  },
  {
    name: 'Choline',
    description: 'An essential nutrient grouped with B vitamins, critical for liver function, brain development, and nerve signalling. The precursor to acetylcholine — the neurotransmitter for memory and muscle control. When a label says "Choline" without specifying the form, it is most likely Choline Bitartrate — the most affordable but lowest brain-uptake form. Better forms: CDP-Choline (Citicoline) and Alpha-GPC for brain health.',
    purpose: 'Supports liver health, brain function, neurotransmitter production (acetylcholine), and fat metabolism',
    safety_notes: 'Safe at recommended doses. High doses (above 3.5g/day as choline) can cause fishy body odour, nausea, and low blood pressure — due to gut bacteria producing trimethylamine. People with TMAU (trimethylaminuria) should use caution. Pregnancy significantly increases choline requirements.',
    is_common_allergen: false,
    category: 'vitamin',
    severity: 'safe',
    bioavailability: 'medium',
    bioavailability_notes: 'Bioavailability varies by form: choline bitartrate ~40%; CDP-choline and alpha-GPC have significantly higher brain uptake. Take with food.',
  },
  {
    name: 'Vitamin D3',
    description: 'Also known as Cholecalciferol. The animal-derived form of Vitamin D — the same form the skin produces from sunlight. The most effective supplemental form for raising blood Vitamin D levels. Requires activation by the liver then kidneys before becoming hormonally active. Essential for calcium absorption, bone strength, immune regulation, and muscle function.',
    purpose: 'Supports bone strength, calcium absorption, immune defence, and mood regulation',
    safety_notes: 'Generally safe. Fat-soluble — excess stored in body fat and can accumulate. Toxicity (causing high blood calcium) is rare but possible at very high doses above 10,000 IU/day long-term. Standard doses (1000–4000 IU/day) are well within safe limits. Blood testing recommended to personalise dose. People with sarcoidosis or certain cancers may have altered Vitamin D metabolism — check with doctor.',
    is_common_allergen: false,
    category: 'vitamin',
    severity: 'safe',
    bioavailability: 'high',
    bioavailability_notes: 'Fat-soluble; take with a meal containing fat for optimal absorption. D3 raises serum 25(OH)D levels more effectively than D2.',
  },
  {
    name: 'Vitamin D2',
    description: 'Plant-derived Vitamin D (ergocalciferol) produced by UV irradiation of ergosterol in yeast or fungi. The vegan alternative to animal-derived D3. Less effective than D3 at raising and sustaining blood 25(OH)D levels; widely used in fortified foods and vegan supplements.',
    purpose: 'Plant-derived Vitamin D for bone health and immune support; suitable for vegans',
    safety_notes: 'Fat-soluble — can accumulate at very high doses. Toxicity risk is low at standard supplemental doses (up to 4,000 IU/day). Blood testing recommended to monitor 25(OH)D levels. People with sarcoidosis, granulomatous diseases, or certain cancers may have altered Vitamin D metabolism — consult a doctor.',
    is_common_allergen: false,
    category: 'vitamin',
    severity: 'safe',
    bioavailability: 'medium',
    bioavailability_notes: 'Less potent than D3 at raising and maintaining serum 25(OH)D levels. Fat-soluble; take with a meal containing fat.',
  },
  {
    name: 'Vitamin D',
    description: 'Umbrella label for Vitamin D when the specific form (D2 or D3) is not disclosed on the label. May be Ergocalciferol (D2) or Cholecalciferol (D3). Both support bone health, calcium absorption, immune function, and mood; D3 is generally more potent at raising blood levels.',
    purpose: 'Supports bone health, calcium absorption, immune function, and mood',
    safety_notes: 'Fat-soluble — can accumulate at very high doses. Toxicity rare at standard doses (up to 4,000 IU/day) but possible above 10,000 IU/day long-term. Blood testing recommended to personalise dose. Consult a doctor if on medications affecting calcium metabolism or if diagnosed with sarcoidosis.',
    is_common_allergen: false,
    category: 'vitamin',
    severity: 'safe',
    bioavailability: 'medium',
    bioavailability_notes: 'Fat-soluble. Form not specified — see Vitamin D3 or D2 entries for specific absorption notes.',
  },
  {
    name: 'Vitamin A',
    description: 'Umbrella label for Vitamin A when the specific form is undisclosed. May be preformed Vitamin A (Retinol or Retinyl Palmitate from animal sources) or provitamin A (Beta-Carotene from plants). Essential for vision, immune defence, skin cell renewal, and reproductive health.',
    purpose: 'Supports vision (especially night vision), immune function, skin cell renewal, and reproductive health',
    safety_notes: 'Risk depends on form. Preformed Vitamin A is teratogenic at excess doses — pregnant women must not exceed 3,000 mcg RAE (10,000 IU) per day. Chronic excess associated with liver damage and increased fracture risk. If form is unspecified, treat with caution during pregnancy. Beta-Carotene form does not carry the same toxicity risk.',
    is_common_allergen: false,
    category: 'vitamin',
    severity: 'caution',
    bioavailability: 'high',
    bioavailability_notes: 'Fat-soluble; well absorbed with dietary fat. Form not specified — preformed Vitamin A (Retinol) is more directly usable than Beta-Carotene.',
  },
  {
    name: 'Retinol',
    description: 'The active preformed form of Vitamin A derived from animal sources, typically supplied as retinyl palmitate or retinyl acetate in supplements. Directly usable by the body without conversion — supports vision, skin cell renewal, immune defence, and foetal development.',
    purpose: 'Active preformed Vitamin A for vision, skin cell renewal, immune function, and growth',
    safety_notes: 'Fat-soluble — accumulates in the liver, creating toxicity risk with excess intake. Chronic doses above 3,000 mcg RAE/day associated with liver damage, bone loss, and increased fracture risk. Strictly teratogenic — pregnant women must keep total daily intake below 3,000 mcg RAE (10,000 IU). High-dose long-term intake may also impair Vitamin D function.',
    is_common_allergen: false,
    category: 'vitamin',
    severity: 'caution',
    bioavailability: 'high',
    bioavailability_notes: 'Fat-soluble; well absorbed with dietary fat. The most directly usable form of Vitamin A — does not require conversion.',
  },
  {
    name: 'Beta-Carotene',
    description: 'A carotenoid pigment found in orange, red, and yellow plants. Serves as provitamin A — the body converts it to retinol as needed, self-regulating to prevent Vitamin A toxicity. Also acts as a fat-soluble antioxidant in its own right, protecting cells from oxidative damage.',
    purpose: 'Provitamin A antioxidant converted to Vitamin A as needed; protects against oxidative stress',
    safety_notes: 'Generally safe — the body self-limits conversion to retinol, avoiding accumulation seen with preformed Vitamin A. Critical exception: high-dose supplementation (≥20 mg/day) in smokers and people with significant asbestos exposure significantly increases lung cancer risk — high-dose isolated Beta-Carotene supplements are contraindicated in these groups. Very high intakes may cause reversible orange skin discolouration (carotenodermia).',
    is_common_allergen: false,
    category: 'vitamin',
    severity: 'caution',
    bioavailability: 'medium',
    bioavailability_notes: 'Conversion to Vitamin A is variable and inefficient (~6:1 ratio). Fat enhances absorption. Conversion is reduced in hypothyroidism and certain genetic variants.',
  },
  {
    name: 'Vitamin E',
    description: 'Umbrella label for Vitamin E when the specific form is undisclosed. Vitamin E is a family of fat-soluble antioxidants protecting cell membranes from oxidative damage. May be alpha-tocopherol, mixed tocopherols, tocotrienols, or a combination; each form has different biological activity and absorption characteristics.',
    purpose: 'Antioxidant protecting cell membranes from oxidative damage; supports immune function and skin health',
    safety_notes: 'High doses (above 400–1,000 IU/day) may impair blood clotting and interact with warfarin, aspirin, and other antiplatelet drugs — consult a doctor if on blood-thinning medications. The SELECT trial linked high-dose Vitamin E supplementation to increased prostate cancer risk in healthy men. Avoid high supplemental doses without clinical supervision.',
    is_common_allergen: false,
    category: 'vitamin',
    severity: 'caution',
    bioavailability: 'medium',
    bioavailability_notes: 'Fat-soluble; take with a meal containing fat. Form not specified — see Alpha-Tocopherol or Mixed Tocopherols for specific notes.',
  },
  {
    name: 'Alpha-Tocopherol',
    description: 'The most biologically active and preferentially retained form of Vitamin E in human tissue, maintained by the hepatic alpha-tocopherol transfer protein. Exists as natural (d-alpha, more bioavailable) and synthetic (dl-alpha, less potent) forms. The predominant Vitamin E form used in supplements.',
    purpose: 'Primary active Vitamin E antioxidant for protecting cell membranes, immune support, and skin health',
    safety_notes: 'High doses (above 400–1,000 IU/day) may increase bleeding risk by inhibiting platelet aggregation and interact with warfarin — caution with anticoagulants. The SELECT trial found increased prostate cancer risk with long-term high-dose supplementation in healthy men. High-dose isolated alpha-tocopherol may also deplete gamma-tocopherol, which has anti-inflammatory roles.',
    is_common_allergen: false,
    category: 'vitamin',
    severity: 'caution',
    bioavailability: 'high',
    bioavailability_notes: 'Fat-soluble; take with food. Natural d-alpha tocopherol is better retained in tissues than synthetic dl-alpha tocopherol.',
  },
  {
    name: 'Mixed Tocopherols',
    description: 'A naturally derived blend of alpha, beta, gamma, and delta tocopherol forms of Vitamin E, extracted from plant oils such as sunflower or soya. Provides broader antioxidant coverage than isolated alpha-tocopherol, with gamma and delta forms contributing additional anti-inflammatory protection.',
    purpose: 'Broad-spectrum Vitamin E complex providing antioxidant protection via alpha, beta, gamma, and delta tocopherol forms',
    safety_notes: 'Generally considered safer than high-dose isolated alpha-tocopherol — broader form profile may reduce associated risks. Still carries bleeding risk at very high doses — caution with warfarin and antiplatelet drugs. Soya-derived products may contain trace soya protein; individuals with severe soya allergy should verify the extraction source.',
    is_common_allergen: false,
    category: 'vitamin',
    severity: 'caution',
    bioavailability: 'medium',
    bioavailability_notes: 'Fat-soluble; take with food. Gamma-tocopherol may offer additional anti-inflammatory benefits beyond alpha-tocopherol alone.',
  },
  {
    name: 'Tocotrienols',
    description: 'A subgroup of Vitamin E comprising alpha, beta, gamma, and delta tocotrienol forms, structurally distinct from tocopherols. Primarily derived from palm oil and annatto. Emerging research suggests cardiovascular, neuroprotective, and anti-inflammatory benefits beyond standard tocopherols, though evidence is less established.',
    purpose: 'Advanced Vitamin E form with potent antioxidant activity and potential cardiovascular and neuroprotective benefits',
    safety_notes: 'Generally considered safe at studied doses (up to 200 mg/day). May interact with blood-thinning medications — caution with warfarin, aspirin, and other antiplatelet drugs. Less characterised than tocopherols; long-term safety data remain limited. Do not take alongside blood thinners without medical supervision.',
    is_common_allergen: false,
    category: 'vitamin',
    severity: 'safe',
    bioavailability: 'medium',
    bioavailability_notes: 'Fat-soluble; better absorbed with food. Palm and annatto-derived tocotrienol-rich fractions are most studied.',
  },
  {
    name: 'Vitamin K1',
    description: 'The primary dietary form of Vitamin K (phylloquinone) found in green leafy vegetables. Activates hepatic clotting factors (II, VII, IX, X) essential for blood coagulation. Also contributes to bone mineralisation via osteocalcin, though Vitamin K2 is more potent for bone health specifically.',
    purpose: 'Essential for blood clotting and bone mineralisation; activates clotting factors produced in the liver',
    safety_notes: 'Critical interaction with warfarin (Coumadin) — Vitamin K1 directly counteracts warfarin\'s anticoagulant mechanism. People on warfarin must maintain consistent daily Vitamin K intake and must not start or adjust supplementation without medical supervision. Generally safe for those not on anticoagulants. No established tolerable upper limit at standard supplemental doses.',
    is_common_allergen: false,
    category: 'vitamin',
    severity: 'caution',
    bioavailability: 'medium',
    bioavailability_notes: 'Fat-soluble; absorption highly variable (10–80%). Dietary fat significantly enhances absorption. Interacts with warfarin — consult a doctor if on anticoagulants.',
  },
];

async function seed() {
  for (const ingredient of ingredients) {
    const embedding = await embed(ingredient.name);

    if (!embedding) {
      console.error(`Failed to embed: ${ingredient.name}`);
      continue;
    }

    await axios.post(`${process.env.BE_SERVICE_URL}/api/ingredients`, {
      ...ingredient,
      embedding
      },
      { headers: { 'x-api-key': process.env.INTERNAL_API_KEY } }
    );

    console.log(`Saved ${ingredient.name}`);
  }
  console.log('Seeding complete')
}

seed().catch(console.error);
