import dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });
import axios from 'axios'
import { embed } from './ollama.js';

const ingredients = [

  // === BIOACTIVE COMPOUNDS ===
  {
    name: 'BPC-157',
    description: 'Body Protection Compound 157 — a synthetic pentadecapeptide (15 amino acids) derived from a protein found in gastric juice. Studied extensively in animal models for gut healing, tendon and ligament repair, bone healing, neuroprotection, and systemic organ protection. Has shown remarkable tissue-healing properties in rodent studies across multiple injury and disease models. NOT approved by the FDA or any major regulatory agency for human use. No completed human randomised controlled trials. Sold as a "research chemical" — often injected subcutaneously or intramuscularly; oral forms exist but bioavailability is highly questionable as the peptide is likely degraded in the stomach.',
    purpose: 'Tissue repair and healing — gut, tendons, ligaments, and neuroprotection (animal research only; no human clinical evidence)',
    safety_notes: 'Not approved for human use by any regulatory agency. No completed human clinical safety or efficacy trials — all evidence is from animal studies. Sourced from unregulated research chemical suppliers — purity and sterility cannot be guaranteed. Injection without medical supervision carries infection and contamination risks. The leap from rodent pharmacology to human benefit is not established. Long-term effects in humans are unknown.',
    is_common_allergen: false,
    category: 'other',
    severity: 'note',
    bioavailability: 'low',
    bioavailability_notes: 'Oral BPC-157 is likely largely degraded by stomach acid and digestive proteases — peptides generally do not survive intact transit to systemic circulation. Injectable forms bypass this issue. The gastric-origin peptide may have local GI effects even orally. Systemic oral bioavailability is unestablished in humans.',
  },
  {
    name: 'Melatonin',
    description: 'A hormone produced by the pineal gland from serotonin — the primary regulator of the circadian rhythm (sleep-wake cycle). Naturally secreted in darkness, suppressed by light (particularly blue light). Strong clinical evidence for: jet lag correction, circadian rhythm disorders (delayed sleep phase syndrome), and shift work adaptation. Modest evidence for general insomnia. Available OTC in the USA at unregulated doses (often 5–10mg); classified as a prescription medicine in the EU, UK, and Australia. The effective dose for circadian entrainment is typically 0.1–0.5mg — far lower than most commercial supplements.',
    purpose: 'Circadian rhythm regulation, jet lag, sleep onset — a hormone supplement with strong evidence for circadian disorders',
    safety_notes: 'Generally safe for short-term use. Most commercial supplements are massively overdosed — 5–10mg vs the effective 0.1–0.5mg dose. Higher doses do not improve sleep and may cause grogginess, vivid dreams, and next-day impairment. Long-term use may theoretically suppress endogenous melatonin production — evidence is limited but warrants caution with prolonged daily use. Timing is critical — taking it at the wrong time can shift the circadian clock in the wrong direction. Interactions with blood thinners, immunosuppressants, and diabetes medications. Avoid with autoimmune conditions (immune-stimulating at higher doses). Not recommended during pregnancy.',
    is_common_allergen: false,
    category: 'other',
    severity: 'note',
    bioavailability: 'medium',
    bioavailability_notes: 'Oral bioavailability is highly variable (3–76%) due to extensive first-pass hepatic metabolism. Peak plasma concentration within 1 hour. Sublingual and liquid forms may improve absorption consistency. The wide bioavailability variation means dosing response differs greatly between individuals.',
  },
  {
    name: 'GABA',
    description: 'Gamma-aminobutyric acid — the primary inhibitory neurotransmitter in the central nervous system. GABA binds GABA-A and GABA-B receptors to reduce neuronal excitability. Supplemental oral GABA is controversial: the traditional view is that GABA does not cross the blood-brain barrier (BBB) in meaningful amounts due to its size and polarity. However, emerging research suggests oral GABA may have peripheral effects via gut-brain axis signalling, and PharmaGABA (a fermented form) may have modest CNS effects. Many popular herbal anxiolytics (passionflower, valerian, lemon balm) work by modulating GABA pathways indirectly.',
    purpose: 'Anxiety relief, sleep support, and relaxation — though direct CNS effects of oral GABA supplementation are debated',
    safety_notes: 'Generally safe and well-tolerated. No significant adverse effects reported at typical supplement doses. The primary limitation is uncertain efficacy for CNS effects — may work peripherally rather than centrally. Additive sedation with CNS depressants (benzodiazepines, alcohol) — caution with these combinations. Not to be confused with pharmaceutical GABA receptor drugs (benzodiazepines, barbiturates, GHB).',
    is_common_allergen: false,
    category: 'amino_acid',
    severity: 'safe',
    bioavailability: 'low',
    bioavailability_notes: 'Oral GABA crosses the blood-brain barrier poorly — the intact molecule is unlikely to reach the CNS in meaningful amounts. Peripheral effects via gut-brain signalling pathways are possible. PharmaGABA (fermented) may have marginally better CNS bioavailability than synthetic GABA.',
  },

  // === ESSENTIAL FATS AND BRAIN HEALTH ===
  {
    name: 'Omega-3',
    description: 'A family of polyunsaturated fatty acids (PUFAs) — the three main forms are EPA (eicosapentaenoic acid) and DHA (docosahexaenoic acid) from marine sources (fish oil, algae oil, krill oil), and ALA (alpha-linolenic acid) from plant sources (flaxseed, chia). EPA and DHA have the most direct clinical evidence: strong evidence for triglyceride reduction (at doses ≥2g/day), anti-inflammatory effects, cardiovascular risk reduction, and DHA is essential for brain and retinal structure. ALA must be converted to EPA/DHA in the body — conversion is inefficient (~5–10% to EPA, <1% to DHA).',
    purpose: 'Cardiovascular health, triglyceride reduction, anti-inflammatory, brain and eye health (EPA and DHA)',
    safety_notes: 'Generally safe. At doses above 3g/day, omega-3 has meaningful blood-thinning (antiplatelet and anticoagulant) effects — caution with warfarin and antiplatelet drugs; discontinue before surgery. High doses may suppress immune function slightly. Fish-sourced omega-3 may contain trace mercury/PCBs — quality matters; molecularly distilled products have minimal contamination. Algae oil is the vegan EPA/DHA source with no contamination concern. Fishy burps (oxidised oil odour) indicate product quality issues or poor enteric coating.',
    is_common_allergen: false,
    category: 'extract',
    severity: 'safe',
    bioavailability: 'high',
    bioavailability_notes: 'EPA and DHA are well-absorbed — triglyceride form (in fish) and re-esterified triglyceride (rTG) forms are best absorbed; ethyl ester form (most common supplement form) is ~30% less bioavailable. Absorption significantly improved when taken with a fat-containing meal. Krill oil phospholipid form is also highly bioavailable. ALA from plant sources is well-absorbed but inefficiently converted to EPA/DHA.',
  },
  {
    name: 'Phosphatidylserine',
    description: 'A phospholipid naturally present in high concentrations in brain cell membranes — an essential structural component of neuronal membranes that supports signal transduction and neurotransmitter activity. Modern supplements use soy-derived or sunflower-derived phosphatidylserine (older products used bovine brain-derived PS, discontinued due to BSE concerns). The FDA has granted a qualified health claim for cognitive decline based on clinical evidence. Well-studied nootropic with consistent evidence for memory, attention, and cognitive function — particularly in elderly populations and cognitively stressed adults.',
    purpose: 'Cognitive function, memory, attention — FDA qualified health claim for cognitive decline prevention',
    safety_notes: 'Generally very safe and well-tolerated. Mild blood-thinning effects — caution with anticoagulants. Soy-derived phosphatidylserine is soy-based — relevant for severe soy allergies (though highly processed, soy protein is largely removed). Sunflower-derived versions are available for soy-sensitive individuals.',
    is_common_allergen: false,
    category: 'extract',
    severity: 'safe',
    bioavailability: 'medium',
    bioavailability_notes: 'Phosphatidylserine is absorbed from the gut, partially broken down to lysophosphatidylserine and serine, then reassembled in tissues. Crosses the blood-brain barrier. Absorption improved with fat-containing meals. The DHA-enriched form (PS-DHA) may have superior brain delivery.',
  },

  // === SUPERFOODS AND ALGAE ===
  {
    name: 'Spirulina',
    description: 'Arthrospira platensis or A. maxima — a blue-green cyanobacterium (photosynthetic bacterium, commonly called an algae) grown in alkaline lakes and cultivated commercially. Exceptionally nutrient-dense: ~60–70% protein by dry weight (complete amino acid profile), phycocyanin (antioxidant blue pigment), B vitamins, iron, gamma-linolenic acid (GLA), and antioxidants. Phycocyanin has anti-inflammatory and antioxidant properties. One of the most protein-dense foods by weight on earth.',
    purpose: 'Nutrient-dense whole food supplement — complete protein, iron, antioxidants (phycocyanin), and B vitamins',
    safety_notes: 'QUALITY CRITICAL: spirulina can be contaminated with microcystins (hepatotoxic cyanotoxins produced by contaminating cyanobacteria) and heavy metals (lead, cadmium, mercury, arsenic) from polluted water sources. Always buy from reputable suppliers with third-party contamination testing. Immune-stimulating properties — caution in autoimmune conditions. Contains significant amounts of vitamin K — people on warfarin should be aware (affects INR). Contains phenylalanine — avoid in phenylketonuria (PKU). May bind and reduce absorption of co-administered medications.',
    is_common_allergen: false,
    category: 'whole_food',
    severity: 'note',
    bioavailability: 'high',
    bioavailability_notes: 'Spirulina lacks the hard cell wall of other algae — protein and nutrients are highly digestible (~85% protein digestibility). Phycocyanin and other pigments are well-absorbed. Iron in spirulina is moderately bioavailable.',
  },
  {
    name: 'Chlorella',
    description: 'A freshwater green microalgae (Chlorella vulgaris, C. pyrenoidosa) with an exceptionally hard cellulose cell wall that must be mechanically disrupted (broken cell wall) to allow nutrient absorption. Among the highest natural sources of chlorophyll. Also provides complete protein (~50–60%), vitamins, minerals, and the Chlorella Growth Factor (CGF). Marketed for heavy metal detoxification — some evidence it binds cadmium, lead, and mercury in the gut, reducing absorption. However, chlorella itself can be contaminated with heavy metals if sourced from polluted water.',
    purpose: 'Nutrient-dense algae supplement — chlorophyll, complete protein, heavy metal binding, immune support',
    safety_notes: 'Quality is critical — contamination with heavy metals and microcystins is a risk from poor quality sources; always use third-party tested products. MUST use "broken cell wall" form for meaningful nutrient absorption — intact cell wall is indigestible. Immune-stimulating properties — caution in autoimmune conditions. Contains significant vitamin K — warfarin users should be aware. Sporopollenin in chlorella can bind to medications and reduce drug absorption — take medications separately. Initial use may cause green-coloured stools (harmless).',
    is_common_allergen: false,
    category: 'whole_food',
    severity: 'note',
    bioavailability: 'medium',
    bioavailability_notes: 'Intact chlorella is largely indigestible due to its hard cellulose cell wall. Broken cell wall preparations significantly improve nutrient bioavailability. Protein digestibility is lower than spirulina (~80% for broken cell wall vs ~85% for spirulina).',
  },
  {
    name: 'Wheatgrass',
    description: 'Young tender shoots of Triticum aestivum (wheat) harvested before the grain forms — typically 7–10 days after germination. At the grass stage, no gluten-containing grain has formed — wheatgrass itself does not contain gluten. However, cross-contamination with wheat grain during harvesting and processing is a real risk. Rich in chlorophyll, vitamins C and E, beta-carotene, iron, calcium, and enzymes. Consumed as fresh juice or dried powder.',
    purpose: 'Alkalising whole food supplement — chlorophyll, vitamins, minerals, and digestive enzymes',
    safety_notes: 'Generally safe. COELIAC AND GLUTEN SENSITIVITY: wheatgrass at the grass stage does not inherently contain gluten — however, cross-contamination with wheat grain is a documented risk in processing. People with coeliac disease should only use wheatgrass certified gluten-free and from dedicated gluten-free facilities. May cause nausea and headache initially — start with small amounts. Home-grown wheatgrass can harbour mould if improperly grown.',
    is_common_allergen: false,
    category: 'whole_food',
    severity: 'safe',
    bioavailability: 'medium',
    bioavailability_notes: 'Nutrients are better extracted in juice form than powder. Chlorophyll is absorbed from the gut in small amounts — its biological significance at supplement doses is unclear. Vitamins and minerals are moderately bioavailable.',
  },
  {
    name: 'Barley Grass',
    description: 'Young shoots of Hordeum vulgare (barley) harvested before grain formation — similar nutritional profile to wheatgrass. Rich in chlorophyll, superoxide dismutase (SOD — a potent antioxidant enzyme), vitamins, minerals, and phytonutrients. Like wheatgrass, the grass stage does not contain gluten — the gluten-forming proteins (hordein) are only in the grain. However, cross-contamination during harvesting and processing is a risk.',
    purpose: 'Alkalising green whole food supplement — chlorophyll, antioxidant enzymes (SOD), vitamins and minerals',
    safety_notes: 'Generally safe. Same cross-contamination concerns as wheatgrass — people with coeliac disease should only use certified gluten-free barley grass from dedicated facilities. May cause initial digestive adjustment (bloating, loose stools) — start with small amounts. Quality matters — poor agricultural practices can introduce pesticide residues.',
    is_common_allergen: false,
    category: 'whole_food',
    severity: 'safe',
    bioavailability: 'medium',
    bioavailability_notes: 'Nutrients more bioavailable in juice form than powder. SOD enzyme is largely degraded by stomach acid — its systemic antioxidant effects are questionable. Vitamins and minerals are reasonably bioavailable.',
  },
  {
    name: 'Moringa',
    description: 'Dried leaf powder from Moringa oleifera — called the "miracle tree" for its exceptional nutritional density. The leaves contain complete protein (~25% by weight), vitamin C (~7× orange), calcium (~4× milk), potassium (~3× banana), iron (~3× spinach), and a range of antioxidant compounds including isothiocyanates (anti-inflammatory). One of the most nutrient-dense plant foods. IMPORTANT: only the leaves and pods are safe for human consumption — the seeds, root, and root bark contain toxins (rotenone, moringine) and should not be consumed.',
    purpose: 'Exceptionally nutrient-dense green supplement — complete protein, iron, calcium, vitamin C, and anti-inflammatory isothiocyanates',
    safety_notes: 'Leaf powder is safe. CRITICAL: only the LEAVES and PODS are safe — the root, root bark, and concentrated seed extracts contain potentially toxic alkaloids and rotenone. Moringa leaf may have mild hypoglycaemic effects — monitor blood sugar with diabetes medications. Contains vitamin K — warfarin users should be aware. Some anti-nutrient content (oxalates, phytates) — can reduce mineral absorption; mitigated by not consuming with other high-mineral foods.',
    is_common_allergen: false,
    category: 'whole_food',
    severity: 'safe',
    bioavailability: 'medium',
    bioavailability_notes: 'Nutrients are moderately bioavailable from the dried leaf. Anti-nutrients (phytates, oxalates) reduce mineral bioavailability somewhat. Vitamin C degrades during drying — fresh moringa leaf has significantly more than dried powder.',
  },
  {
    name: 'Acai Berry',
    description: 'Small purple berry from Euterpe oleracea palm trees native to the Amazon rainforest. One of the highest antioxidant values (ORAC) of any food — due to very high anthocyanin content (particularly cyanidin glycosides), oleic acid (healthy monounsaturated fat), dietary fibre, and polyphenols. Fresh acai perishes within hours — commercial acai is processed as frozen pulp or freeze-dried powder. Marketing claims about weight loss and detoxification have been greatly overstated relative to actual evidence.',
    purpose: 'Antioxidant-rich whole food supplement — anthocyanins, polyphenols, healthy fats, and fibre',
    safety_notes: 'Generally very safe. Fresh or unprocessed acai from endemic regions may carry Trypanosoma cruzi (Chagas disease parasite) — only commercially processed (pasteurised/freeze-dried) acai is safe. Marketing claims about weight loss, detoxification, and miraculous health effects are not supported by evidence — these are marketing, not science.',
    is_common_allergen: false,
    category: 'whole_food',
    severity: 'safe',
    bioavailability: 'medium',
    bioavailability_notes: 'Anthocyanins are moderately absorbed (~5–12% bioavailability) — rapidly metabolised and excreted. Fat content in acai may improve absorption of fat-soluble polyphenols. Freeze-dried powder retains anthocyanin content better than heat-dried.',
  },
  {
    name: 'Goji Berry',
    description: 'Dried berries from Lycium barbarum or L. chinense — Himalayan and Chinese wolfberries with a long history in Traditional Chinese Medicine. Rich in zeaxanthin and lutein (eye health carotenoids), polysaccharides (LBPs — Lycium barbarum polysaccharides with immunomodulatory properties), betaine, vitamin C, and antioxidants. Used traditionally for eye health, energy, immune support, and longevity. Contains the anti-aging antioxidant zeaxanthin at very high concentrations — one of the best dietary sources.',
    purpose: 'Eye health (zeaxanthin), immune support, antioxidant, Traditional Chinese Medicine adaptogen',
    safety_notes: 'DRUG INTERACTION: Goji berry interacts with warfarin — multiple documented clinical cases of significantly elevated INR leading to bleeding events. Avoid goji berry with warfarin or any anticoagulant without medical supervision. May interact with diabetes and blood pressure medications (mild hypoglycaemic and hypotensive effects). Goji belongs to the Solanaceae (nightshade) family — people with nightshade allergies should be cautious.',
    is_common_allergen: false,
    category: 'whole_food',
    severity: 'note',
    bioavailability: 'medium',
    bioavailability_notes: 'Zeaxanthin and lutein are fat-soluble carotenoids — absorption improved with fat-containing meals. Polysaccharides (LBPs) are partially absorbed and partially fermented by gut bacteria. Zeaxanthin from goji is highly bioavailable relative to other dietary sources.',
  },
  {
    name: 'Cranberry Powder',
    description: 'Dried and powdered fruit from Vaccinium macrocarpon (cranberry). Active compounds are Type A proanthocyanidins (PACs) — unique to cranberries, these PACs prevent type P-fimbriated E. coli from adhering to the epithelial cells of the urinary tract. This anti-adhesion mechanism is the basis for cranberry\'s evidence-based role in reducing recurrent UTI frequency. Cranberry does NOT treat an active UTI — it only reduces adherence to prevent new infections.',
    purpose: 'UTI prevention — reduces recurrent UTI frequency by preventing E. coli adhesion to the urinary tract; also antioxidant',
    safety_notes: 'Safe at typical supplement doses. Cranberry is NOT an antibiotic — do NOT use to treat an active UTI; seek medical treatment. May increase the effect of warfarin (though evidence is conflicting — monitor INR if on warfarin). Very high doses of cranberry juice (not powder) can promote kidney stone formation in calcium oxalate stone-formers (high oxalate content).',
    is_common_allergen: false,
    category: 'whole_food',
    severity: 'safe',
    bioavailability: 'medium',
    bioavailability_notes: 'Type A PACs reach the urinary tract intact — their anti-adhesion activity is exerted in the urine, not systemically. Bioavailability of anthocyanins and other polyphenols is moderate (~5–12%). Standardised PAC content (36mg PACs is the researched dose) is more important than the total cranberry powder weight.',
  },
  {
    name: 'Blueberry Powder',
    description: 'Dried and powdered wild or cultivated blueberries (Vaccinium corymbosum or V. angustifolium). Rich in anthocyanins (particularly delphinidin, cyanidin, malvidin glycosides), pterostilbene (a methylated resveratrol with better bioavailability), quercetin, and chlorogenic acid. Among the most studied fruits for cognitive benefits — consistent evidence for improved memory, executive function, and neuroprotection. Also studied for blood pressure reduction, gut microbiome support, and cardiovascular health.',
    purpose: 'Cognitive support, antioxidant, blood pressure, and gut microbiome — one of the most evidence-backed whole food supplements for brain health',
    safety_notes: 'Generally very safe. One of the safest and most well-tolerated whole food supplements. High in vitamin K — warfarin users should be aware of consistent intake. Wild blueberry (V. angustifolium) has higher anthocyanin content than cultivated varieties.',
    is_common_allergen: false,
    category: 'whole_food',
    severity: 'safe',
    bioavailability: 'medium',
    bioavailability_notes: 'Anthocyanins are moderately absorbed (5–12%) and rapidly metabolised. Pterostilbene has significantly higher bioavailability than structurally similar resveratrol (~80% vs ~1%). Gut bacteria metabolise unabsorbed polyphenols to smaller bioactive metabolites.',
  },
  {
    name: 'Flaxseed',
    description: 'Seeds of Linum usitatissimum — one of the richest plant sources of ALA (alpha-linolenic acid, the plant omega-3), dietary fibre (both soluble and insoluble), and lignans (phytoestrogens converted by gut bacteria to enterolignans). Lignans have weak oestrogenic and anti-oestrogenic properties depending on context — studied for hormone-related cancer prevention. Must be GROUND for meaningful nutrient absorption — whole flaxseeds pass through largely undigested. Provides more omega-3 (ALA) per gram than any other common food.',
    purpose: 'Plant omega-3 (ALA), dietary fibre, and lignans — gut health, cardiovascular support, hormonal balance',
    safety_notes: 'Generally safe. MUST be ground for bioavailability — whole seeds largely pass through undigested. Store ground flaxseed refrigerated and use within weeks — flaxseed oil is highly prone to oxidation (rancidity). Contains cyanogenic glycosides (linamarin) that can release trace hydrogen cyanide — not relevant at dietary amounts but avoid consuming very large quantities of raw flaxseed. Lignan phytoestrogens may theoretically affect hormone-sensitive conditions (breast cancer, endometriosis) — evidence is contradictory, with some evidence showing protective effects. High fibre — adequate fluid intake essential.',
    is_common_allergen: false,
    category: 'whole_food',
    severity: 'safe',
    bioavailability: 'medium',
    bioavailability_notes: 'Ground flaxseed is essential for nutrient release. ALA bioavailability from ground flaxseed is good but conversion to EPA/DHA is inefficient (~5–10% to EPA, <1% to DHA). Lignans are converted by gut bacteria to enterodiol and enterolactone — bioavailability depends heavily on gut microbiome composition.',
  },
  {
    name: 'Chia Seeds',
    description: 'Seeds of Salvia hispanica — native to central Mexico. Excellent source of ALA omega-3 (the highest % of any seed by weight), soluble dietary fibre (forms a gel absorbing 10–12× their weight in water), complete protein, calcium, magnesium, and phosphorus. The soluble fibre gelling property slows gastric emptying, moderates glucose absorption, and supports gut health. Unlike flaxseed, chia seeds can be consumed whole (the outer coating breaks down sufficiently in the gut).',
    purpose: 'Plant omega-3 (ALA), soluble fibre, complete protein, calcium — gut health and blood sugar moderation',
    safety_notes: 'Generally safe. IMPORTANT: always consume with adequate water — dry chia seeds absorb large amounts of fluid and can cause choking or oesophageal obstruction if swallowed dry without liquid. At least one documented case of oesophageal obstruction in a patient with a history of swallowing difficulties. High fibre — introduce gradually to avoid GI discomfort. Same ALA-to-EPA/DHA conversion inefficiency as flaxseed.',
    is_common_allergen: false,
    category: 'whole_food',
    severity: 'safe',
    bioavailability: 'medium',
    bioavailability_notes: 'ALA is well-absorbed but inefficiently converted to EPA/DHA. The mucilaginous coating on chia seeds breaks down in the gut — whole seeds are sufficiently bioavailable unlike whole flaxseed. Calcium bioavailability from chia is moderate (oxalate content reduces absorption somewhat).',
  },
  {
    name: 'Hemp Seeds',
    description: 'Seeds of Cannabis sativa — contain no significant THC or CBD (cannabinoids are concentrated in flowers and leaves, not seeds). A rare plant-based complete protein (~25% protein) with an optimal omega-6 to omega-3 ratio (approximately 3:1) — the ratio most associated with reduced inflammation. Contains gamma-linolenic acid (GLA), arginine, magnesium, zinc, and iron. The hull (outer shell) contains most of the fibre; hulled hemp seeds (hemp hearts) are the most common supplement form.',
    purpose: 'Complete plant protein, omega-3 and omega-6 in optimal ratio, magnesium, zinc — vegan nutrition and anti-inflammatory',
    safety_notes: 'Generally safe. Contain negligible THC/CBD — not psychoactive and not a concern for most people. DRUG TESTING CAVEAT: at very high consumption levels (multiple tablespoons daily), trace THC from hemp seeds has occasionally caused positive drug tests in sensitive workplace screening — a very rare concern at typical supplement doses. Not a concern for the vast majority of users. People with cannabis allergy may react (shared proteins).',
    is_common_allergen: false,
    category: 'whole_food',
    severity: 'safe',
    bioavailability: 'high',
    bioavailability_notes: 'Hemp seed protein is highly digestible (~91–98% PDCAAS-corrected). All essential amino acids present in good proportions. Fats are well-absorbed. GLA is absorbed and can be converted to anti-inflammatory prostaglandins.',
  },
  {
    name: 'Psyllium Husk',
    description: 'The outer husks (seed coats) of Plantago ovata seeds — composed of approximately 70% soluble fibre (arabinoxylan) that forms a thick gel when hydrated. The most evidence-backed dietary fibre supplement available. Strong clinical evidence for: LDL cholesterol reduction (FDA health claim for cardiovascular disease risk), blood glucose moderation (slows carbohydrate absorption), constipation relief, IBS symptom improvement, and stool bulking. Mechanism is purely mechanical — slows gastric emptying, traps bile acids (lowering cholesterol), and feeds gut bacteria.',
    purpose: 'Soluble fibre — LDL cholesterol reduction, blood sugar moderation, constipation, IBS, and gut health',
    safety_notes: 'Generally very safe. MUST be taken with a full glass of water — psyllium absorbs water rapidly and can cause choking or intestinal obstruction if taken dry. Take with adequate water at all times. May reduce absorption of co-administered medications — take medications at least 1 hour before or 2–4 hours after psyllium. Initial use may cause gas and bloating as gut bacteria ferment the fibre — start with a small dose and increase gradually.',
    is_common_allergen: false,
    category: 'whole_food',
    severity: 'safe',
    bioavailability: 'na',
    bioavailability_notes: 'Psyllium is not absorbed — it acts purely mechanically in the GI tract. It is fermented by colonic bacteria to a limited extent (lower fermentability than most fibres, which is why it causes less gas than inulin or FOS).',
  },

  // === PROTEINS ===
  {
    name: 'Whey Protein',
    description: 'The soluble protein fraction of milk, separated during cheese production. A complete protein containing all essential amino acids and particularly high in branched-chain amino acids (BCAAs) — leucine, isoleucine, and valine. Leucine content (~10–11%) is the highest of any whole-food protein source and is the primary trigger for muscle protein synthesis (MPS). Three main forms: concentrate (70–80% protein, more lactose and fat), isolate (>90% protein, minimal lactose — better for lactose intolerance), and hydrolysate (pre-digested for fastest absorption). Fastest-absorbing protein supplement available.',
    purpose: 'Muscle building and recovery — highest leucine content of any protein, fastest absorption, most evidence for muscle protein synthesis',
    safety_notes: 'Safe for healthy adults. DAIRY/MILK ALLERGY: whey is derived from milk — genuine milk protein allergy is a contraindication (different from lactose intolerance). LACTOSE INTOLERANCE: concentrate contains lactose; isolate and hydrolysate have minimal lactose — use isolate if sensitive. Not suitable for vegans. Very high protein intake (>2.5g/kg body weight) may stress kidneys in people with pre-existing kidney disease — not a concern for healthy kidneys.',
    is_common_allergen: true,
    category: 'extract',
    severity: 'safe',
    bioavailability: 'high',
    bioavailability_notes: 'Highest bioavailability of any protein supplement (PDCAAS and DIAAS scores close to 1.0). Rapidly digested and absorbed — peak amino acid levels within 60–90 minutes. Hydrolysate absorbs fastest. High leucine content maximally stimulates muscle protein synthesis. Biological value (BV) of ~104 — the highest of any food protein.',
  },
  {
    name: 'Pea Protein',
    description: 'Protein isolate derived from yellow split peas (Pisum sativum). A high-quality plant-based protein with a good amino acid profile — particularly rich in BCAAs (leucine, isoleucine, valine) but relatively low in methionine (the limiting amino acid). Hypoallergenic, vegan, and gluten-free — one of the most well-tolerated plant proteins. Often combined with brown rice protein to create a complete amino acid profile that compensates for each other\'s limiting amino acids. Growing evidence for muscle building comparable to whey in some studies.',
    purpose: 'Vegan complete protein — muscle building, satiety, hypoallergenic — ideal for dairy-free and plant-based diets',
    safety_notes: 'Generally very safe. One of the most hypoallergenic protein sources available. Contains purines — relevant at very high doses for people with gout. Pea protein is one of the least allergenic food proteins. Well-tolerated in people who react to dairy, soy, egg, and other common protein sources.',
    is_common_allergen: false,
    category: 'extract',
    severity: 'safe',
    bioavailability: 'medium',
    bioavailability_notes: 'Protein digestibility is good (~98% PDCAAS when combined with rice protein). Moderately well-absorbed. The methionine limitation means it should ideally be combined with a complementary protein for optimal muscle protein synthesis. Slower absorption than whey — more similar to casein kinetics.',
  },
  {
    name: 'Brown Rice Protein',
    description: 'Plant-based protein extracted from brown rice (Oryza sativa) — produced by enzymatically digesting the starch, leaving a concentrated protein fraction. Lower in lysine (the limiting amino acid) but relatively high in methionine — the opposite limitation to pea protein, making them ideal complementary partners. Hypoallergenic, vegan, and easily digestible. Often combined with pea protein to achieve a complete amino acid profile approaching whey in muscle-building studies.',
    purpose: 'Vegan plant protein — typically combined with pea protein for a complete amino acid profile; hypoallergenic',
    safety_notes: 'Generally very safe. Hypoallergenic. Brown rice protein may contain trace arsenic (inorganic) from rice — a concern at very high intake from rice-based products; choose brands that test for heavy metals. Not suitable for people with rice allergy (rare).',
    is_common_allergen: false,
    category: 'extract',
    severity: 'safe',
    bioavailability: 'medium',
    bioavailability_notes: 'Protein digestibility is good but limited by lysine content when used alone. Combined with pea protein (pea:rice 70:30 or 60:40), the amino acid profile and muscle protein synthesis response approaches whey. Moderately slower absorption than whey.',
  },
  {
    name: 'Colostrum',
    description: 'The first milk produced by mammals in the 24–72 hours after birth — used commercially as bovine colostrum from dairy cows. Vastly different from regular milk: concentrated with immunoglobulins (IgA, IgG, IgM), lactoferrin (antimicrobial), growth factors (IGF-1, TGF-β), cytokines, and proline-rich polypeptides (PRPs). Used in supplements for immune support, gut health and integrity (reducing intestinal permeability), and athletic performance (due to IGF-1 content). IGF-1 is a growth factor with anabolic effects.',
    purpose: 'Immune support, gut integrity, and athletic performance — concentrated immunoglobulins, growth factors, and lactoferrin',
    safety_notes: 'Generally safe. Derived from bovine dairy — not suitable for people with milk allergy or vegans. ATHLETES: bovine colostrum is on the WADA watch list — IGF-1 content is a concern for drug-tested athletes; check with sport\'s anti-doping authority before use. Most immunoglobulins (IgG, IgM) are largely degraded by stomach acid before absorption — systemic immune effects from oral IgG are questionable; local gut effects are more plausible. Lactoferrin and growth factors may have better stability.',
    is_common_allergen: false,
    category: 'whole_food',
    severity: 'note',
    bioavailability: 'medium',
    bioavailability_notes: 'Immunoglobulins are largely degraded in the GI tract — systemic IgG absorption is limited in healthy adults with intact gut barriers. Local effects on gut mucosa are more significant. Lactoferrin is partially resistant to digestion. IGF-1 is absorbed in small amounts. Growth factors may act locally on the gut epithelium even without systemic absorption.',
  },

  // === BEE PRODUCTS ===
  {
    name: 'Bee Pollen',
    description: 'Flower pollen collected by honeybees, mixed with nectar and bee salivary enzymes, formed into granules. One of the most nutritionally complete natural foods — contains protein (~25%), carbohydrates, fats, vitamins (B vitamins, vitamin C, E), minerals, enzymes, and antioxidant flavonoids. Also contains varying amounts of pollen from diverse plant species. Used for energy, allergy desensitisation (controversial), athletic performance, and general nutrition. Nutritional composition varies widely depending on floral source.',
    purpose: 'Nutritionally dense whole food supplement — protein, vitamins, minerals, enzymes, and antioxidant flavonoids',
    safety_notes: 'SIGNIFICANT ALLERGEN RISK. Bee pollen contains pollen from multiple plant species — can trigger severe allergic reactions including anaphylaxis in people with pollen allergies, bee allergies, or general atopic conditions (asthma, eczema, hay fever). Multiple deaths from anaphylaxis following bee pollen supplementation have been reported. Never use bee pollen if you have known pollen, bee, or plant allergies without medical supervision. People with no allergy history should still start with a tiny amount (a few granules) and observe for 30–60 minutes before taking a full dose.',
    is_common_allergen: true,
    category: 'whole_food',
    severity: 'note',
    bioavailability: 'medium',
    bioavailability_notes: 'Nutritional bioavailability from bee pollen granules is variable — the outer sporopollenin shell resists digestion, limiting release of contents. Mechanically disrupted (cracked) bee pollen may have better bioavailability. Enzymes in bee pollen are largely denatured by stomach acid.',
  },
  {
    name: 'Royal Jelly',
    description: 'A white, creamy secretion produced by worker honeybee glands — fed exclusively to queen bee larvae and adult queens, responsible for the queen\'s differentiated development and extended lifespan. Contains water (~67%), proteins (particularly royalactin — the protein that triggers queen differentiation), 10-hydroxy-2-decenoic acid (10-HDA, a unique fatty acid with antimicrobial and biological properties), vitamins (B5, B6), and minerals. Used for immune support, skin health, blood pressure lowering, and general vitality.',
    purpose: 'Immune support, blood pressure lowering, skin health, and anti-ageing — unique compounds including royalactin and 10-HDA',
    safety_notes: 'ALLERGEN RISK — less severe than bee pollen on average but serious allergic reactions including anaphylaxis have been reported. People with bee or bee-product allergies should avoid. Asthmatic individuals are at higher risk of allergic reaction. Blood pressure lowering effects — caution with antihypertensive medications (additive effect). Do not use during pregnancy or breastfeeding (insufficient safety data; some hormonal activity).',
    is_common_allergen: false,
    category: 'whole_food',
    severity: 'note',
    bioavailability: 'medium',
    bioavailability_notes: '10-HDA is absorbed from the GI tract and has measurable systemic activity. Proteins including royalactin are largely digested. 10-HDA retains activity after digestion. Freeze-dried forms preserve bioactive components better than heat-dried.',
  },

  // === WHOLE FOOD SUPPLEMENTS ===
  {
    name: 'Cacao',
    description: 'Raw, minimally processed Theobroma cacao — the least processed form of chocolate, made by cold-pressing raw cacao beans to separate the fat (cacao butter) from the solid (cacao powder), without roasting. Retains significantly higher flavanol content than cocoa powder, which is made from roasted beans (heat destroys flavanols). Contains the same active compounds as cocoa: flavanols (epicatechin), theobromine (mild stimulant), small amounts of caffeine, magnesium, iron, and antioxidant polyphenols. TOXIC to dogs and cats due to theobromine.',
    purpose: 'Raw high-flavanol cacao — superior antioxidant and flavanol content compared to conventional cocoa powder',
    safety_notes: 'Generally safe for humans. TOXIC to dogs and cats — theobromine causes seizures and cardiac arrest in these animals. Mild stimulant effects from theobromine and caffeine — sensitive individuals and those with cardiac arrhythmias should be aware. Higher flavanol content than cocoa powder means stronger cardiovascular and cognitive effects. May interact with MAOIs. Raw cacao contains phytic acid — may slightly reduce mineral absorption from the same meal.',
    is_common_allergen: false,
    category: 'whole_food',
    severity: 'safe',
    bioavailability: 'medium',
    bioavailability_notes: 'Cacao flavanols (epicatechin) are moderately well-absorbed — higher bioavailability than Dutch-process cocoa because raw processing preserves the flavanol structure. Theobromine is well-absorbed. Fat (cacao butter) improves absorption of fat-soluble compounds.',
  },
  {
    name: 'MCT Oil',
    description: 'Medium-chain triglyceride (MCT) oil — a concentrated extract from coconut oil or palm kernel oil, fractionated to isolate medium-chain fatty acids (C8 caprylic acid, C10 capric acid, and sometimes C12 lauric acid). Unlike long-chain fats, MCTs bypass the lymphatic system and are absorbed directly into the portal circulation, transported to the liver, and rapidly oxidised to ketones — an alternative fuel source for the brain and muscles. C8 (caprylic acid) is the most ketogenic and most studied; some products are 100% C8.',
    purpose: 'Rapid energy source and ketone production — ketogenic diet support, cognitive fuel, fat loss (modest evidence)',
    safety_notes: 'Safe for most people. Common side effect: GI distress (diarrhoea, nausea, cramping) at high doses — start low (1 tsp) and increase gradually. Pure C8 MCT tends to cause more GI side effects than blended C8/C10. Not recommended for people with liver disease (MCTs are processed primarily by the liver). Derived from coconut or palm kernel — people with coconut allergy should exercise caution. Provides 8.3 kcal/g — not calorie-free despite being used in weight management.',
    is_common_allergen: false,
    category: 'extract',
    severity: 'safe',
    bioavailability: 'high',
    bioavailability_notes: 'MCTs are absorbed directly into the portal vein without requiring bile acids or chylomicron assembly — much faster than long-chain fats. Rapidly transported to the liver and oxidised to ketones (beta-hydroxybutyrate, acetoacetate). Peak ketone elevation within 1–2 hours of consumption.',
  },
  {
    name: 'Oat Fibre',
    description: 'Indigestible dietary fibre derived from oat (Avena sativa) bran — distinct from oat beta-glucan (a specific soluble fibre fraction from oats). Oat fibre is primarily insoluble cellulose and hemicellulose, used as a bulking agent and dietary fibre supplement. Oat beta-glucan is the component with the FDA health claim for cholesterol reduction — oat fibre (as labelled) may not have the same beta-glucan content unless specifically indicated. Used for digestive support, satiety, and blood sugar moderation.',
    purpose: 'Dietary fibre supplement — digestive health, satiety, and blood sugar moderation',
    safety_notes: 'Generally safe. OATS AND GLUTEN: oats are naturally gluten-free but heavily cross-contaminated with wheat, barley, and rye in most processing facilities. People with coeliac disease require certified purity-tested gluten-free oats. A small subset of coeliac patients also react to avenin (oat protein) even in pure oats — these individuals must avoid all oats. Adequate fluid intake essential with high fibre intake.',
    is_common_allergen: false,
    category: 'whole_food',
    severity: 'safe',
    bioavailability: 'na',
    bioavailability_notes: 'Insoluble fibre is not absorbed — passes through the GI tract largely intact, adding bulk to stool and supporting gut motility. Soluble oat beta-glucan (if present) forms a gel that slows nutrient absorption.',
  },
  {
    name: 'Coconut Water Powder',
    description: 'Spray-dried or freeze-dried powder of the clear liquid endosperm from young green coconuts (Cocos nucifera). A natural electrolyte drink — very high in potassium (~600mg per 240ml serving of fresh coconut water), moderate sodium, magnesium, and calcium. Lower sodium content than most sports drinks — better for hydration in everyday or moderate exercise situations; may be insufficient for high-intensity exercise with heavy sweat loss. Contains natural sugars (primarily glucose and fructose, ~6g per 240ml).',
    purpose: 'Natural electrolyte replenishment — potassium-rich hydration for everyday activity, light exercise, and hangover recovery',
    safety_notes: 'Generally very safe. Very high potassium content — relevant for people with kidney disease (impaired potassium excretion — can cause dangerous hyperkalaemia) or those taking potassium-sparing diuretics or ACE inhibitors. Not ideal for high-intensity exercise with heavy sweating — sodium content is too low to replace sweat losses effectively (use sports drinks with higher sodium for intense exercise). Derived from coconut — people with tree nut/coconut allergy should exercise caution.',
    is_common_allergen: false,
    category: 'whole_food',
    severity: 'safe',
    bioavailability: 'high',
    bioavailability_notes: 'Electrolytes (potassium, sodium, magnesium) are well-absorbed. Natural sugars are rapidly absorbed. Reconstituted powder retains similar electrolyte profile to fresh coconut water.',
  },
  {
    name: 'Turmeric Powder',
    description: 'Dried and ground Curcuma longa rhizomes — the whole food form of turmeric, as opposed to turmeric extract (standardised for curcuminoids). Contains approximately 2–5% curcuminoids (vs 95% in standardised extract). Also retains essential oils (turmerones), starch, and fibre from the whole rhizome matrix. Used in cooking (curry) and as a whole-food supplement. The food form has been used in traditional medicine for millennia. At culinary and whole-food doses, the curcumin content is much lower than in extracts — different dosing expectations apply.',
    purpose: 'Anti-inflammatory and antioxidant whole food spice — traditional Ayurvedic and culinary use with lower curcumin content than extracts',
    safety_notes: 'Generally safe at culinary and supplement doses. Same precautions as turmeric extract at high doses: mild blood-thinning effects and caution with anticoagulants before surgery. The whole-food matrix (turmerones, oils) may improve curcumin absorption compared to isolated curcumin. Distinguishing from turmeric EXTRACT: whole powder requires higher amounts for equivalent curcuminoid dose.',
    is_common_allergen: false,
    category: 'whole_food',
    severity: 'safe',
    bioavailability: 'low',
    bioavailability_notes: 'Curcuminoid bioavailability from whole turmeric powder is poor but slightly better than isolated curcumin due to the presence of turmerones (essential oils) that may assist absorption. Black pepper (piperine) significantly increases curcumin absorption. Fat in the meal improves absorption of lipophilic curcuminoids.',
  },
  {
    name: 'Ginger Powder',
    description: 'Dried and ground Zingiber officinale rhizomes — the whole food form of ginger, distinct from ginger extract. The drying process converts many gingerols to shogaols (which are more potent anti-inflammatory compounds). Contains ~1–4% gingerol/shogaol equivalents depending on origin and processing — lower than standardised extract but retains the full matrix of volatile oils, starch, and fibre. Used widely in cooking and as a whole-food supplement for nausea, digestion, and anti-inflammation.',
    purpose: 'Anti-nausea, digestive support, anti-inflammatory — whole food form of ginger for general use',
    safety_notes: 'Generally safe at culinary and supplement doses. Same mild blood-thinning precautions as ginger extract apply at higher doses. GI irritation at very high doses. Generally considered safe in pregnancy for nausea at dietary amounts — consult a doctor for supplement doses.',
    is_common_allergen: false,
    category: 'whole_food',
    severity: 'safe',
    bioavailability: 'medium',
    bioavailability_notes: 'Shogaols (formed during drying of gingerols) are more bioavailable than gingerols. Both are moderately absorbed from the gut. Dried ginger has a different pharmacological profile from fresh ginger due to this gingerol-to-shogaol conversion.',
  },
  {
    name: 'Black Seed',
    description: 'Seeds of Nigella sativa (also called black cumin, kalonji, habbatus sauda) — an annual flowering plant native to South and Southwest Asia. Used in Islamic traditional medicine (mentioned in Hadith as a cure for "everything except death"). The primary active compound is thymoquinone, with additional volatile oils, alkaloids, and flavonoids. Well-studied for anti-inflammatory, antimicrobial, antioxidant, and immune-modulating properties. Evidence for: blood sugar reduction, blood pressure lowering, asthma, and immune support.',
    purpose: 'Anti-inflammatory, immune modulation, blood sugar and blood pressure support — significant traditional use (Islamic medicine) with modern research backing',
    safety_notes: 'Generally well-tolerated. Blood sugar lowering effects — monitor with diabetes medications (additive hypoglycaemic risk). Blood pressure lowering — monitor with antihypertensives. May inhibit CYP2D6 and CYP3A4 enzyme activity — potential interactions with medications metabolised by these enzymes. Thymoquinone is an antioxidant at normal doses but may become pro-oxidant at very high concentrations. Avoid during pregnancy — has uterine-stimulating effects at high doses (used historically as an abortifacient).',
    is_common_allergen: false,
    category: 'herb',
    severity: 'note',
    bioavailability: 'medium',
    bioavailability_notes: 'Thymoquinone is lipophilic — absorption improved with fat-containing meals. Volatile oils are well-absorbed from the GI tract. Black seed oil has higher and more consistent thymoquinone bioavailability than the whole seed.',
  },
  {
    name: 'Maca Powder',
    description: 'Dried and ground root of Lepidium meyenii — the whole food powder form of maca, distinct from maca root extract. Contains the same bioactive compounds (glucosinolates, macamides, minerals, amino acids) at lower concentrations than concentrated extracts. The traditional Andean use involves consuming large amounts of the dried root — the supplement powder mirrors this whole-food approach. Gelatinised maca (cooked to remove starch) may have better digestibility and slightly more concentrated active compounds than raw maca powder.',
    purpose: 'Adaptogen and superfood — libido, energy, mood, and hormonal balance in whole food form',
    safety_notes: 'Generally safe. Same precautions as maca root extract at high doses: glucosinolate content may affect thyroid function in people with thyroid conditions at very high doses. Gelatinised form may be better tolerated than raw maca powder for people with sensitive digestion. May cause insomnia if taken late in the day.',
    is_common_allergen: false,
    category: 'whole_food',
    severity: 'safe',
    bioavailability: 'medium',
    bioavailability_notes: 'Macamides and other active compounds are reasonably bioavailable from the whole powder. Gelatinised maca removes the starch for slightly improved active compound concentration and digestibility.',
  },

  // === B VITAMINS ===
  {
    name: 'Thiamine HCl',
    description: 'Thiamine hydrochloride — the standard, water-soluble supplemental form of thiamine (vitamin B1). An essential coenzyme for carbohydrate and branched-chain amino acid metabolism (pyruvate dehydrogenase, alpha-ketoglutarate dehydrogenase, transketolase). Critical for nerve and cardiac function. Deficiency causes wet beriberi (cardiac failure), dry beriberi (peripheral neuropathy), and Wernicke-Korsakoff syndrome (in alcoholism). Active transport absorption becomes saturated at high doses — passive diffusion then contributes at higher intakes.',
    purpose: 'Vitamin B1 supplementation — carbohydrate metabolism, nerve function, cardiac health, and energy production',
    safety_notes: 'Excellent safety profile. Very well-tolerated — no established upper limit with no reports of toxicity from oral intake. Water-soluble — excess is excreted in urine. Alcoholism significantly depletes thiamine — thiamine supplementation is standard in alcohol use disorder management. People with heavy alcohol use should ensure adequate thiamine.',
    is_common_allergen: false,
    category: 'vitamin',
    severity: 'safe',
    bioavailability: 'medium',
    bioavailability_notes: 'Absorbed via active transport (saturable at doses >5mg) and passive diffusion at higher doses. Bioavailability decreases as dose increases. Converted in tissues to the active coenzyme thiamine pyrophosphate (TPP). Far less bioavailable than fat-soluble benfotiamine.',
  },
  {
    name: 'Benfotiamine',
    description: 'A fat-soluble, synthetic S-acyl derivative of thiamine (vitamin B1). Unlike water-soluble thiamine HCl, benfotiamine passively diffuses across cell membranes and is not limited by the active transport saturation of standard thiamine. Produces blood and tissue thiamine levels approximately 3.6× higher than equivalent doses of thiamine HCl. More effectively crosses the blood-brain barrier. Studied for diabetic neuropathy (significant evidence), cognitive function (Alzheimer\'s disease research), and AGE (advanced glycation end-product) inhibition.',
    purpose: 'Superior-bioavailability vitamin B1 — diabetic neuropathy, cognitive support, AGE inhibition, and elevated tissue thiamine levels',
    safety_notes: 'Generally very safe. Better tolerated and more effective than standard thiamine HCl at equivalent doses. No significant adverse effects identified at typical supplement doses. Fat-soluble — take with a fat-containing meal for optimal absorption.',
    is_common_allergen: false,
    category: 'vitamin',
    severity: 'safe',
    bioavailability: 'high',
    bioavailability_notes: 'Passively absorbed across cell membranes — not limited by active transport saturation. Achieves blood and tissue levels ~3.6× higher than equivalent doses of thiamine HCl. Converted inside cells to thiamine and thiamine pyrophosphate (TPP). Better blood-brain barrier penetration than standard thiamine.',
  },
  {
    name: 'Riboflavin-5-Phosphate',
    description: 'The active, phosphorylated coenzyme form of riboflavin (vitamin B2) — also called Flavin Mononucleotide (FMN). Unlike standard riboflavin, which must be converted to FMN and then FAD (flavin adenine dinucleotide) in the body, riboflavin-5-phosphate is already in the active coenzyme form. FAD and FMN are essential cofactors for the electron transport chain, fatty acid oxidation, and the conversion of folate, pyridoxine (B6), and niacin to their active forms. Some people with compromised liver function or riboflavin kinase activity benefit from the pre-activated form.',
    purpose: 'Active vitamin B2 coenzyme — energy production, antioxidant support, and activation of other B vitamins',
    safety_notes: 'Excellent safety profile. Riboflavin causes harmless bright yellow/green fluorescent urine — this is normal and expected. No toxicity reported. Water-soluble — excess excreted. Riboflavin-5-phosphate may be better absorbed by people with specific metabolic conditions than standard riboflavin.',
    is_common_allergen: false,
    category: 'vitamin',
    severity: 'safe',
    bioavailability: 'high',
    bioavailability_notes: 'Riboflavin-5-phosphate (FMN) is dephosphorylated in the gut to free riboflavin before absorption, then rephosphorylated in the intestinal wall — absorption may be modestly superior to standard riboflavin in people with impaired riboflavin kinase. Well-absorbed overall.',
  },
  {
    name: 'Calcium Pantothenate',
    description: 'The calcium salt of pantothenic acid (vitamin B5) — the most common and stable supplemental form. Pantothenic acid is an essential component of coenzyme A (CoA) — the central molecule in fatty acid synthesis, the Krebs cycle, steroid hormone synthesis, haemoglobin synthesis, and neurotransmitter production. The "panto" in pantothenic means "everywhere" — it is found in virtually all foods. Deficiency is extremely rare in healthy individuals eating a varied diet. Often included in B-complex supplements and supports adrenal gland function.',
    purpose: 'Vitamin B5 supplementation — coenzyme A production, energy metabolism, adrenal support, and hormone synthesis',
    safety_notes: 'Excellent safety profile — one of the safest vitamins. No established upper limit. Very well-tolerated. Diarrhoea reported only at very high doses (several grams daily). Water-soluble — excess excreted. Deficiency is virtually non-existent in people eating any varied diet.',
    is_common_allergen: false,
    category: 'vitamin',
    severity: 'safe',
    bioavailability: 'high',
    bioavailability_notes: 'Calcium pantothenate is readily hydrolysed to pantothenic acid in the gut and well-absorbed. Converted to CoA in cells through a multi-step phosphorylation pathway.',
  },
  {
    name: 'Vitamin B3',
    description: 'Niacin (nicotinic acid) — the flushing form of vitamin B3, distinct from niacinamide (nicotinamide) which does not cause flushing. At nutritional doses (14–16mg NE/day), it prevents pellagra (B3 deficiency disease). At pharmacological doses (1.5–3g/day, under medical supervision), niacin is one of the most effective agents for raising HDL cholesterol and lowering triglycerides — a therapeutic use requiring medical oversight. Also an NAD+ precursor. The prostaglandin D2-mediated skin flushing (redness, warmth, tingling) is niacin\'s most notable side effect — harmless but uncomfortable.',
    purpose: 'Vitamin B3 (niacin form) — NAD+ precursor, energy metabolism; at pharmacological doses: HDL raising and triglyceride lowering',
    safety_notes: 'FLUSHING: niacin causes significant skin flushing — redness, warmth, and tingling — particularly on the face, neck, and chest. Onset ~15–30 minutes after ingestion, lasting ~30–60 minutes. Harmless but can be alarming. Taking aspirin 30 minutes before reduces flushing. Take with food. Extended-release (ER) niacin reduces flushing but has greater risk of serious hepatotoxicity (liver damage) — ER niacin should only be used under medical supervision with liver monitoring. Raises blood sugar and uric acid — caution in diabetes and gout. Pharmacological doses (1.5g+) require medical supervision.',
    is_common_allergen: false,
    category: 'vitamin',
    severity: 'note',
    bioavailability: 'high',
    bioavailability_notes: 'Well-absorbed from the GI tract. Converted to NAD+ and NADP+ in tissues. At pharmacological doses, the liver converts excess niacin to trigonelline and other metabolites. Extended-release forms slow absorption to reduce peak plasma concentrations that cause flushing.',
  },
  {
    name: 'Niacinamide',
    description: 'Nicotinamide — the non-flushing amide form of vitamin B3. Does NOT cause the prostaglandin-mediated flushing of niacin (nicotinic acid). At nutritional doses, functions identically to niacin as an NAD+ precursor and essential coenzyme. At pharmacological doses, niacinamide does NOT raise HDL or lower triglycerides — a key pharmacological difference from niacin. Used for skin health (acne, rosacea, melasma — topically and orally), cognitive support, NAD+ precursor activity (though less efficiently than NMN or NR at equivalent doses), and general B3 supplementation.',
    purpose: 'Non-flushing vitamin B3 — NAD+ precursor, skin health (acne, rosacea), and cognitive support without niacin flush',
    safety_notes: 'Generally very safe. No flushing unlike niacin. At very high doses (>3g/day), niacinamide may cause GI upset, liver enzyme elevation, and headache — less hepatotoxic than extended-release niacin but high-dose monitoring is advisable. Does not raise HDL or lower triglycerides — do not substitute for niacin therapy without understanding this distinction.',
    is_common_allergen: false,
    category: 'vitamin',
    severity: 'safe',
    bioavailability: 'high',
    bioavailability_notes: 'Well-absorbed from the GI tract. Converted to NAD+ via the Preiss-Handler pathway. Unlike NMN and NR which are more direct NAD+ precursors, niacinamide is converted to NAD+ through an additional metabolic step.',
  },
  {
    name: 'Vitamin B6',
    description: 'Pyridoxine — the most common supplemental form of vitamin B6, a water-soluble vitamin that must be converted to pyridoxal 5-phosphate (P-5-P) in the liver to act as a coenzyme. Essential for amino acid metabolism (over 100 enzyme reactions), neurotransmitter synthesis (serotonin, dopamine, GABA, norepinephrine), red blood cell formation, and immune function. The B6 involved in homocysteine metabolism (with B12 and folate). CRITICAL SAFETY NOTE: chronic vitamin B6 supplementation at doses above 50–100mg/day causes peripheral neuropathy (nerve damage) — a serious and potentially irreversible adverse effect.',
    purpose: 'Vitamin B6 — amino acid metabolism, neurotransmitter synthesis, red blood cell production, and homocysteine regulation',
    safety_notes: 'PERIPHERAL NEUROPATHY RISK. Chronic intake above 50mg/day (and some reports at even lower doses with prolonged use) causes sensory peripheral neuropathy — numbness, tingling, burning pain in the hands and feet, and loss of proprioception. This effect is dose-dependent and duration-dependent. Most cases resolve after stopping supplementation, but may be slow or incomplete. The EU has lowered the safe upper limit to 12mg/day for supplements. Check total B6 content across all supplements — B-complex products often contain high doses. Symptoms: tingling or numbness in extremities — stop supplementation immediately if these develop.',
    is_common_allergen: false,
    category: 'vitamin',
    severity: 'note',
    bioavailability: 'medium',
    bioavailability_notes: 'Pyridoxine is absorbed from the gut and converted to pyridoxal 5-phosphate (P-5-P) in the liver. People with liver dysfunction or genetic variants may have impaired conversion — P-5-P (pre-activated B6) bypasses this step.',
  },
  {
    name: 'Pyridoxal 5-Phosphate',
    description: 'The active coenzyme form of vitamin B6 (P-5-P) — directly usable by the body without requiring hepatic conversion from pyridoxine. Pyridoxal phosphate is the biochemically active form that directly participates as a coenzyme in over 100 enzyme reactions involving amino acid metabolism, neurotransmitter synthesis, and homocysteine metabolism. Preferred by people with compromised liver function, those who respond poorly to pyridoxine (HCl), or those with genetic variants affecting B6 metabolism. Same nerve damage (peripheral neuropathy) risk as pyridoxine at high doses.',
    purpose: 'Active vitamin B6 coenzyme — amino acid metabolism, neurotransmitter synthesis, and homocysteine management; pre-activated form for direct use',
    safety_notes: 'Same peripheral neuropathy risk as pyridoxine at high doses — do NOT exceed safe upper limits (50mg/day as a conservative threshold; EU recommends 12mg/day maximum). The active form does not eliminate the neuropathy risk — high-dose P-5-P is equally capable of causing nerve damage. Better choice than pyridoxine for people with liver issues or conversion problems. Stop immediately if tingling or numbness develop in extremities.',
    is_common_allergen: false,
    category: 'vitamin',
    severity: 'note',
    bioavailability: 'high',
    bioavailability_notes: 'Directly absorbed and utilised without hepatic conversion — bypasses the pyridoxine kinase and oxidase steps required for pyridoxine activation. Better bioavailability than standard pyridoxine particularly in people with impaired liver function.',
  },
  {
    name: 'Folate',
    description: 'The naturally occurring, food-form vitamin B9 — specifically referring to 5-methyltetrahydrofolate (5-MTHF or L-methylfolate), the biologically active form. Distinct from synthetic folic acid (which requires enzymatic conversion to the active form via DHFR and MTHFR enzymes). Essential for DNA synthesis, cell division, red blood cell formation, and the one-carbon metabolism cycle (homocysteine conversion to methionine). Critical during pregnancy — prevents neural tube defects. MTHFR gene variants (C677T, A1298C) — affect approximately 40% of the population — reduce folic acid conversion efficiency. These individuals benefit significantly from pre-methylated folate (5-MTHF) supplementation.',
    purpose: 'Vitamin B9 — DNA synthesis, cell division, neural tube defect prevention, and homocysteine management; active form bypasses MTHFR conversion',
    safety_notes: 'Generally safe. Folate (5-MTHF) does not mask B12 deficiency — a concern with high-dose folic acid (synthetic form). Adequate folate is critical during pregnancy and preconception — neural tube defects can occur in the first weeks of pregnancy before many women know they are pregnant. People with MTHFR gene variants should use methylfolate (5-MTHF) rather than folic acid. Folate may mask megaloblastic anaemia of B12 deficiency — always ensure adequate B12 alongside folate supplementation.',
    is_common_allergen: false,
    category: 'vitamin',
    severity: 'safe',
    bioavailability: 'high',
    bioavailability_notes: '5-MTHF (methylfolate) is directly absorbed and used — no MTHFR enzyme conversion required. Bioavailability is approximately 85–100%. Folic acid (synthetic) requires DHFR and MTHFR enzymatic conversion — bioavailability varies by individual MTHFR status. Food folate bioavailability is ~50%.',
  },
  {
    name: 'Vitamin B12',
    description: 'Cobalamin — an essential water-soluble vitamin involved in DNA synthesis, red blood cell maturation (prevents megaloblastic anaemia), and neurological function (myelin sheath maintenance). Found exclusively in animal products — deficiency is common in vegans and vegetarians, the elderly (reduced gastric intrinsic factor), and people on metformin (reduces B12 absorption). Multiple supplemental forms: cyanocobalamin (synthetic, cheapest, least bioactive), methylcobalamin (active form, preferred for neurological support), adenosylcobalamin (mitochondrial active form), and hydroxocobalamin (injectable standard).',
    purpose: 'Essential B12 supplementation — red blood cell production, neurological health, and DNA synthesis; critical for vegans, elderly, and metformin users',
    safety_notes: 'Generally very safe — no established upper limit; excess is excreted in urine. Important: B12 deficiency causes irreversible neurological damage if untreated for extended periods — do not ignore early deficiency symptoms (tingling extremities, fatigue, cognitive impairment, anaemia). Vegans and vegetarians MUST supplement. Metformin users should monitor B12 levels annually. Elderly individuals with atrophic gastritis lack intrinsic factor — oral high-dose B12 is still partially absorbed (passive diffusion), but sublingual or injectable forms are more reliable. Methylcobalamin is generally preferred over cyanocobalamin for neurological applications.',
    is_common_allergen: false,
    category: 'vitamin',
    severity: 'safe',
    bioavailability: 'medium',
    bioavailability_notes: 'Standard absorption requires intrinsic factor (produced by gastric parietal cells) — active transport limited to ~1.5–2mcg per dose. At very high doses (500–1000mcg), approximately 1% is absorbed via passive diffusion — allowing oral high-dose supplementation to work even without intrinsic factor. Methylcobalamin and hydroxocobalamin are better retained in tissues than cyanocobalamin. Sublingual absorption bypasses the intrinsic factor requirement.',
  },

];

async function seed() {
  for (const ingredient of ingredients) {
    const embedding = await embed(ingredient.name);

    if (!embedding) {
      console.error(`Failed to embed: ${ingredient.name}`);
      continue;
    }

    await axios.post(`${process.env.BE_SERVICE_URL}/api/ingredients`, {
      ...ingredient,
      embedding
      },
      { headers: { 'x-api-key': process.env.INTERNAL_API_KEY } }
    );

    console.log(`Saved ${ingredient.name}`);
  }
  console.log('Seeding complete')
}

seed().catch(console.error);
